### ISSUE TITLE
tlh genes

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1000]
From PMID: 27183912

"There are four tlh paralogues within the S. pombe genome (although only two are currently annotated and have their transcription measured using the tiling arrays; C. Norbury, personal communication). One paralogue is located within the sub-telomeric regions of each of the four telomeres for S. pombe chromosomes 1 and 2 (S. pombe has three chromosomes and the sub-telomeric regions of chromosome 3 are unique as they consist of rDNA repeats). "

**Comment by ValWood** [comment]
WHats the action.

I think this should actually say 
"There are four tlh paralogues within the S. pombe genome (although only two are currently *part of the Sequenced genome* C. Norbury, personal communication).

We know there are 4 copies in the genome from some hybridisation data, and it isn't a surprise because the sequences at the ends of chr 1&2 are 99-100% identical over  a large range >50kb, I don't remember exactly.

The "transcription measured" is a bit non-sensical because these 4 sequences are presumed to be *identical*, there is no way that you could distinguish any of the 4  from tiling array data....

So I'll close this because I'm not sure that there is anything to do? but re-open if there is...
v
