### ISSUE TITLE
transporter relationship display query

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1008]
What determines what relationship is displayed on gene pages?

I was looking at 
![display the text](https://cloud.githubusercontent.com/assets/7359272/17779424/7ef3329a-655f-11e6-9591-ca7611b2cc0b.jpg)

and I can't work out why 

GO:0035673 oligopeptide transmembrane transporter activity
dislays 'transports'

but its descendant
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0015421
displays "has substrate"

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0015421#term=ancchart

**Comment by ValWood** [comment]
Also, does anyone know if we have a ticket for more meaningful display of the PR:ID field?

proably gene name and PRO description?
i.e for this 
genex, proteolytic cleavage product
(I'm not sure which one this is...maybe its any/all?)

Anyway if anyone can let me know I can open a ticket for this if necessary?

**Comment by mah11** [comment]
> and I can't work out why [display anomaly]

It may be because GO:0015421 has two is_a parents, of which one (GO:0035673) is in the transporter branch, but the other (GO:0015440) is in the catalytic activity branch. 'Transports' would make more sense, but I don't know how to "teach" the display system to prefer the transporter branch (and that ATP is the meaningful 'substrate' for an ATPase).

> Also, does anyone know if we have a ticket for more meaningful display of the PR:ID field?

We don't. Bear in mind that some of the PR:nn term names are a bit scary ...

    id: PR:000027529
    name: DNA replication regulator sld2 phosphorylated 1 (Schizosaccharomyces pombe)

    id: PR:000027578
    name: histone H3.1, initiator methionine removed methylated 1 (Schizosaccharomyces pombe)

**Comment by ValWood** [comment]
> We don't. Bear in mind that some of the PR:nn term names are a bit scary ...

OK, it isn't as big an issue as I thought....I thought we only had the PRO id, for a gene which was bound, but we do it this way 

http://www.pombase.org/spombe/result/SPAC6B12.11#go-molecular_function
Protein binding
binds rad4, active form PR:000027529
so maybe just showing the  description on mouse over would be enough?

**Comment by ValWood** [comment]
> but I don't know how to "teach" the display system to prefer the transporter branch (and that ATP is the meaningful 'substrate' for an ATPase).

I thought we had other situations like this in the  original configuration that Mark used? maybe not ...do we need some sort of "precedence" for choosing the relation type?

**Comment by ValWood** [comment]
The solution for this  restrict so that everything below
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0015421#term=ancchart
to "transports" rather than "has_substrate"

Need to ask Kim how to do this...

**Comment by ValWood** [comment]
@kimrutherford 
we should ask Kim about this tomorrow.
@mah11  could you describe issue?

**Comment by mah11** [comment]
this already isn't an issue in pombase 2 - see the mam2 gene page

I'll open the website ticket anyway because it'll still be useful for the other reasons we discussed (e.g. consistency with Canto), but the problem in legacy pombase was absence-of-config taking precedence over configured-display, and new pombase is more sensible than that.

**Comment by ValWood** [comment]
p2 still does this:
http://pombase2.aska.gen.nz/gene/SPBC25B2.02c
Its mam1, not mam2...

**Comment by mah11** [comment]
Oops, mistyped the gene name, but it was mam2 I looked at.

Oddly, I thought I didn't see has_substrate displayed yesterday - they all had transports, at least in my head. That's kind of annoying, because at best, we'll have to wait for Kim to extend the config options, and then I'll have to put in a dodgy hack to get the the term1-minus-term2 thing to help (at worst, even the hack won't work).
