### ISSUE TITLE
"regulation of cell growth"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1011]
Hi Antonia,
 
Is "regulation of cell growth" correct here?
curs/21507585ab1a2dfc/ro/

(is regulation of cell size: more accurate?)

"regulation of cell growth" is not used for anything else (mainly because I think growth is a bit nebulous and anything transcription, translation, is ultimately part of cell growth....

Although I'm also not sure whey there is no relationship between cell growth and cell size...I'll look into this when you have given feedback...

Val

**Comment by ValWood** [comment]
or is it NETO?
GO:0051519 activation of bipolar cell growth

**Comment by Antonialock** [comment]
I think cell growth is the correct term to use here (polo is needed to restart growth, following growth arrest due to stresses), but I tweaked it to:
intracellular signal transduction involved in positive regulation of cell growth 
and also added (based on additional data)
intracellular signal transduction involved in positive regulation of G2/M transition of mitotic cell cycle 

![screen shot 2016-09-07 at 13 14 56](https://cloud.githubusercontent.com/assets/12727506/18311667/75c52b08-74fd-11e6-99ee-814b0f14022c.png)

Do you disagree?

Question:
is "recovery from arrest" 
(i.e. stress -> cessation of growth -> repair/acclimatization -> resumption of growth ("recovery from arrest")
= re-entry into mitotic cell cycle, OR is it part of the "response to stress" (but at the end of the response)?

**Comment by ValWood** [comment]
I don't know but I think what you have done sounds fine....again, probably a model is the  best way to approach the signalling pathways to get the annotation consistent

**Comment by ValWood** [comment]
http://www.ncbi.nlm.nih.gov/pubmed/15917811

**Comment by ValWood** [comment]
OK, I don't think it will be correct here to annotation to "cell cycle re-entry"

This is only for re-entry after leaving the cell cycle, not after  a 'checkpoint' type arrest  which is in place in a normal cell cycle...otherwise all of the  DNA integrity checkpoints would also be a type of "cell-cycle re-entry'

It's just 
1. 'positive regulation of G2/M transition' for the cell cycle part, we know that plo1 is upstream of both wee1 and cdc25  in  2 upstream networks:
https://github.com/pombase/curation/issues/1049
But I'm not sure *exactly* how pom1 links to cdc25 and wee1 (the question marks above)

and 
2.  whatever the appropriate "regulation of growth" term

**Comment by Antonialock** [comment]
after thinking about this again...I agree about " pausing" the cell cycle (as opposed to exiting) --> term removed (we had another ticket about this). Also hapy now to remove the growth term.

**Comment by ValWood** [comment]
I think the growth term is OK...its a branched pathway and plo1 does have a role in growth as well as G2/M....
(there might be a GO term no longer required here...)

**Comment by Antonialock** [comment]
argh yeah,

**Comment by Antonialock** [comment]
ok so we have posreg of cell size....I dont mind whichever growth or size, sounds the same to me. You need one to have the other. I annotated map2 to neg reg of size from here
https://github.com/pombase/curation/issues/1043

**Comment by ValWood** [comment]
I thought map2 was the negative pheromone, why is that negatively regulating cell size...does it regulate plo1?
