### ISSUE TITLE
Editing a genotype

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1081]
From Jacky's helpdesk ticket: https://rt.sanger.ac.uk/Ticket/Display.html?id=548540
@jvhayles

Hi Jacky

Do you need to alter the genotype highlighted in grey here?

![edit](https://cloud.githubusercontent.com/assets/7359272/18906119/1deb17b4-855e-11e6-9f5f-bfc5f0b74fcb.jpg)

If so, editing genotypes is easy, from the genotype management page (this one)

Click the link "edit details"
You will get a warning to say that you are trying to edit a genotype with existing annotation (this is fine if you do)
Then you can  make the edits to the genotype and save.

Let me know if this isn't what you wanted to do.

Have you also noticed that if you have made a complicated genotype, and you need a similar one you can "copy and edit" from here. This will make a copy of the genotype with no annotations to edit into a new genotype.

If this doesn't solve your problem, send me more details or Skype me.
val

**Comment by ValWood** [comment]
> PS I am also having trouble with the expression levels as it does not show not assayed which is what I need

This might also solve the above issue as you can edit the expression here too.
Let me know if not.

**Comment by mah11** [comment]
Jacky's problem is that Canto never offers the "not assayed" option for a wild type allele.

That, in turn, is because we didn't foresee anyone doing an experiment quite the way it was done in the paper Jacky is curating - with the human Cdc2 present they don't know whether the level of wild type pombe Cdc2 is the same as without the human copy, whereas we thought people would always know whether they'd changed the level of wt or not. In other words, Jacky's found an edge case.

So we have to decide which is better, less confusing, etc.: tolerate the slightly inaccurate "wild type product level" for pombe cdc2+ in this paper, or allow "not assayed" for wild type everywhere (or at least in all the same cases where "wild type product level" would be allowed.

**Comment by ValWood** [comment]
OK. How are we representing endogenous expression of human cdc2?

**Comment by mah11** [comment]
> How are we representing endogenous expression of human cdc2?

erm, that would only happen in human cells ...

Jacky has put CDC2HS in the background, which makes sense because we can only use pombe genes in the rest of the genotype addition interface.

**Comment by ValWood** [comment]
exogenous

for ref pombe/curs/1ff973d4c300af54

so I think here cdc2
cdc2
CDC2HS his3-27 leu1-32 h-	
cdc2+[Overexpression]
cdc2+[Wild type product level]

 It  is the human gene which is over expressed?

I have a sneaky way of dealing with these older experiments where a human gene is expressed in a pombe WT. I skipped them....I figured that  we weren't losing a lot of information because the things they are showing we usually know anyway.
However  if there is useful information we could flag these to revisit if we have a way to capture trans-genes from another species.

**Comment by mah11** [comment]
I gathered from Jacky's email that there are two strains, each with human CDC2 expressed, one with pombe cdc2+ overexpressed and the other with pombe cdc2+ expression not assayed. I don't think she said explicitly whether human CDC2 is "overexpressed" and I'm not sure how much sense it would make to set the expression level for an exogenous gene whose normal expression level in pombe would obviously be null. What would count as "endogenous level" for an exogenous gene?

For this paper I would suggest to Jacky that we all pretend that we know pombe cdc2+ is at wild type level in the strain that's not known to be overexpressing it. That's a much smaller fudge than changing Canto for a few old experiments.
