### ISSUE TITLE
cellular protein localization

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1083]
I added this to the "GO terms not to annotate, we should always be able to specify to where"
There are quite a lot of violations from the old annotation (in artemis) which will disappear gradually either by adding specificity or converting to phenotypes.

These are the only ones in canto

SPAC10F6.12c.1      GO:0034613  cellular protein localization   8622e3e232348e8d    PomBase
SPAC10F6.12c.1      GO:0034613  cellular protein localization   8622e3e232348e8d    PomBase
SPAC10F6.12c.1      GO:0034613  cellular protein localization   8622e3e232348e8d    PomBase

**Comment by Antonialock** [comment]
downstream...removed..

**Comment by ValWood** [comment]
so what does the methylation do (interested), is it some aspect of maturation? or don't we know?

**Comment by Antonialock** [comment]
So as far as I understand it...

Pombe makes two different pheromones: P-factor (made by h+ cells) and M-factor (made by h-). M and P factor are very different peptides. P-factor is a hydrophilic molecule (and exported from the cell by vesicle transport). M-factor on the other hand is very hydrophobic (due in part to it being methylated) - because it is modified it is harder to synthesise in the lab (which is why a lot of mating assays are done using h- and not h+). Being hydrophobic, the peptide is kept close to the intracellular membranes as it is being tranported out of the cell (via the ATP transporter ste6)- I would guess it doesn't venture far from the cell once outside either whereas I would guess that P factor is very diffusible (so perhaps this influences how the cells physically shmoo - pure speculation now - maybe h- cells grow 'uncontrollably' because P factor is everywhere, and maybe h+ cells in turn "home in" on h- cells because the M factor is very localized. 

This pathway (modification of CAAX motifs) is conserved in human and linked to disease...(the ste6 ortholog is an MDR)

**Comment by ValWood** [comment]
I would expect to see this term

GO:0071587 CAAX-box protein modification
The covalent alteration of one or more amino acid residues within the CAAX box region of CAAX box proteins.
(A f-p link between  these might be useful?)

but what is this modification for...Isn't it part of a "protein targeting" process"

**Comment by ValWood** [comment]
Maybe not
"It is usually assumed that prenyl groups (3-methyl-but-2-en-1-yl) facilitate attachment to cell membranes, similar to lipid anchors like the GPI anchor, though direct evidence is missing."
