### ISSUE TITLE
which DNA damage checkpoint

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1086]
SPAC26A3.02.1		GO:0072421	detection of DNA damage stimulus involved in DNA damage checkpoint	7b4c9e930c511158	PomBase
SPAC26A3.02.1		GO:0072421	detection of DNA damage stimulus involved in DNA damage checkpoint	7b4c9e930c511158	PomBase

**Comment by ValWood** [comment]
Also
tel1 GO:1904291 - positive regulation of mitotic DNA damage checkpoint 
G1 or G2?

**Comment by ValWood** [comment]
rhp18	mitotic DNA damage checkpoint

**Comment by mah11** [comment]
myh1: From the interaction with Hus1, probably intra-S but I'd appreciate a second pair of eyes to confirm, and even to make sure we should have any GO annotation at all (also see submission comment about nuances that can't be captured).
(note to self GO:0072427; will update if Val agrees)

tel1: The annotation is attributed to a paper I haven't worked on (Antonia curated it; I probably just fixed something small for logs in Canto). G1 vs G2 wasn't obvious to me from a quick glance, but if A doesn't remember and doesn't have time to check I can take a closer look later. @antonialock

rhp18: looks like this annotation has been removed some time since the v60 release; the paper hasn't been curated in Canto (PMID:11523791)

set9: has G2 (GO:0007095) in Artemis and in the latest-release GAF; it's an old IMP annotation, so I have no idea why it didn't reach the v60 GAF and gene page. The paper hasn't been curated in Canto (PMID:15550243).

**Comment by Antonialock** [comment]
I had a look at tel1 but I'm really not confident about the checkpoint stuff and I don't know if we can say what phase (maybe it is "obvious" if you know a lot of other things). 

There's quite a few BPs assigned from this session, it probably wouldn't hurt if someone else reviews them..

**Comment by mah11** [comment]
OK, I had another look at the paper for tel1 (forgot the PMID earlier - it's 15226425 session d2288b20e67eb62d). I'm not any more confident about checkpoint stuff than Antonia (or than I was yesterday), but I could tentatively lean towards the G2 damage checkpoint for tel1 and rad3 because the stuff in the paper draws in crb2 and chk1, which are both annotated to the G2 term.

**Comment by ValWood** [comment]
I'd assumed if a checkpoint was annotated it would be possible to know which one, perhaps not....

The only paper in pombe which has annotations for G1 DNA damage checkpoint is
http://amigo.geneontology.org/amigo/reference/PMID:19033384
Title
The G1-S checkpoint in fission yeast is not a general DNA damage checkpoint.

I think only G2 is really studied ...

**Comment by ValWood** [comment]
I won't worry about this  for now, it can sit in the  log file until we know.
