### ISSUE TITLE
pom1 	establishment of mitotic actomyosin contractile ring localization

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1170]
- [X] pom1 is annotated to 	
establishment of mitotic actomyosin contractile ring localization
but this should probably be changed to
mitotic cytokinesis, site selection

- [x] Also tea1 and tea4:
Tea1, Tea4, and Pom1 also impart negative signal to prevent cell division at cell tips (Almonacid et al., 2009; Celton- Morizur et al., 2006; Huang et al., 2007; Padte et al., 2006). Together with positive signals conferred by the nucleus through the protein Mid1 (Almonacid et al., 2009), negative signals from cell tips define the position of cell division at midcell.

(these are a bit indirect I think, ignoring for now)

**Comment by ValWood** [comment]
I wonder if 
"establishment of mitotic actomyosin contractile ring localization"
should not exist.

Isn't the site selection the thing which determines  "establishment of mitotic actomyosin contractile ring localization"? 

It only has 2 EXP annotation, both PomBase, pom1 and bgs4

**Comment by ValWood** [comment]
Mutants specifically defective in each of these pro- cesses have been identified and constitute the pos, mid, and pom mutants defective in positioning of the division site (Edamatsu and Toyoshima 1996; Sohrmann et al. 1996; Bahler and Pringle 1998; Bahler et al. 1998a; Paoletti and Chang 2000); the rng mutants defective in assembly of the medial acto-myosin ring (Balasubra- manian et al. 1992, 1994, 1998; McCollum et al. 1995; Chang et al. 1996; Bezanilla et al. 1997; Chang et al. 1997; Gould and Simanis 1997; Kitayama et al. 1997; May et al. 1997; Motegi et al. 1997; Eng et al. 1998; Naqvi et al. 1999; Wong et al. 2000); the sid (septation initiation defective) mutants defective in the initiation of septum deposition (Nurse and Thuriaux 1976 Marks et al. 1992; Schmidt et al. 1997; Balasubraman- ian et al. 1998; Sparks et al. 1999; Chang and Gould 2000; Guertin et al. 2000; Hou et al. 2000; Salimova et al. 2000); and the sep mutants defective in cell separation (Sipiczki et al. 1993; Grallert et al. 1999; Ribar et al. 1999; Zilahi et al. 2000a,b).

we should check these when we do cytokinesis project because  some rng are annotated to  septum formation, which seems indirect.

Misht hep to begin from a more recent review and work backwards....

**Comment by ValWood** [comment]
done the pom1 part, the big list of papers is for cytokinesis minproject
https://github.com/pombase/curation/issues/2315
