### ISSUE TITLE
GIST mapping, query about existing multi-allele annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1176]
I am working through to see how much we can automate, and trying to find eg sessions for each scenario.

In this session:
https://curation.pombase.org/pombe/curs/f76448cf5f73c99d/ro/

1. Do you know which multigene phenotype the synthetic rescue applies to
2. Can we say anything about the expressivity of the single and double mutants  to say if the severity of the double mutants are greater of less? (presumably we know WT)

There is no hurry for this...I just thought I'd take a look.....

**Comment by mah11** [comment]
> Do you know which multigene phenotype the synthetic rescue applies to [?]

Well, I reviewed the session recently enough that I can tell (it's FYPO:0001742, which is partially suppressed), but I think it would be tough to get that in any automated way, even if we added severity extensions. The mus81 rad51 double mutant has several phenotypes, of which some do and others don't differ from one or the other single mutant.


> Can we say anything about the expressivity of the single and double mutants to say if the severity of the double mutants are greater or less?

For chromosome loss, gene conversion, and isochromosome formation, maybe - we would have to draw some totally arbitrary boundaries to determine what's low vs. medium vs. high, and there's a fair bit of noise. (I didn't add extensions because Tako didn't, suggesting it wasn't super-important to him, and it'll be a right PITA to edit so many annotations :P )
