### ISSUE TITLE
specifying nucleotide sequence deletion coordinates

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1207]
we have never specified whether these coordinates should be calculated based on mRNA or pre-mRNA

I am currently describing a deleted intron, hence I am using premRNA...but I bet we haven't always (I pretty much always use amino acid coordinates as that's what is usually in the paper, so its probably not a big issue)

**Comment by ValWood** [comment]
assumption default numbering starts at first and last nucleotide of the reference coding sequence.

However, if we ever need to describe a mutant intron we will use the syntax g appended to the nucleitide description nd the genomic coordinates(only if we really have to)

**Comment by ValWood** [comment]
decision default description is  spliced.

- [ ] 1Check exiting by asking Kim to run query
- [ ] fix any that refer to unspliced
- [ ]  document everywhere that to describe an unspliced sequence alteration tag 

1-7-unspliced

**Comment by ValWood** [comment]
I think we can assume  that legacy ones refer to spliced.
We proba bly need some documentation. Do we need a prompt in Canto ?

**Comment by mah11** [comment]
Are there any annotations to change, or is this ticket now just to edit documentation?

**Comment by ValWood** [comment]
I  was going to make a  (possibly dangerous?) assumption that all existing nucleotide  annotations use proceed RNA coordinates. 
However, I have a) no idea how many nucleotide allles we have, or an easy way to check. I am basing this on the fact that this one is the only one I can think of.

So, yes, let's just document how to specify that the allele refers to unspliced RNA...

**Comment by mah11** [comment]
I'm looking at this ticket again because I actually have to use it. There's an intron change - T inserted after chr1 1670566, in gta2 - reported in PMID:32142608, but I'm a bit confused about what to do. This part of an earlier comment

> if we ever need to describe a mutant intron we will use the syntax g appended to the nucleotide description and the genomic coordinates (only if we really have to

suggests that the description should be 1670566-Tg. Correct?

That's fine, but it leaves me really unclear about what this other bit from the same comment means:

> Document everywhere that to describe an unspliced sequence alteration tag
> e.g. 1-7-unspliced

Is it a suggestion for naming alleles? If not, what is it? If it's for the allele description it appears to conflict with the previous part.

The curation itself isn't urgent (Rasmus' session; I can put it through without adding this one), but obvs I'd need to understand what you want so I can document it accurately.

**Comment by ValWood** [comment]
Shall we discuss tomorrow morning?

**Comment by mah11** [comment]
ok

**Comment by ValWood** [comment]
All nucleotide mutant description should be splice/mature transcript.
If this is not possible because intron is mutated append -pt to the description (or primary transcript)

**Comment by mah11** [comment]
OK, I've committed some edits to the documentation. The structure got a little complicated so I'll check it when it's live before I close this.

**Comment by mah11** [comment]
Done! I did some edits a few days ago; Kim got them into live Canto docs yesterday, and I've just now remembered to close this ticket.
