### ISSUE TITLE
priority paper, phosphatase substrates

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1253]
![priortiy paper](https://cloud.githubusercontent.com/assets/7359272/21596150/1aafbf56-d12f-11e6-878f-ecaed15550c6.jpg)

**Comment by ValWood** [comment]
This paper is called " A proteome -wide search for PP2A substrates" but there is only one substrate recorded. Is that correct? or is there a modification spreadsheet hanging around somewhere? There is also no ppa1 or 2 annotation. 
It might be OK but it just struck me as odd?

**Comment by mah11** [comment]
I got curious, so I looked, and ...

Gpd1 really is the only protein unambiguously shown to be a direct PP2A substrate in that paper. They did two major experiments. One found PP2A interactors (BioGRID curated them), and it's possible that PP2A might bind a few of them without dephosphorylating them. The other identified proteins with altered levels and/or 2-D protein gel mobility. For the mobility shifts they didn't even rule out other modifications accounting for some, and even some phosphorylation differences could be due to indirect effects.

**Comment by ValWood** [comment]
so do they show what gpd1 is phosphorylated by, or is that ambiguous?
(there is no kinase/substrate annotation)

**Comment by mah11** [comment]
I didn't read it that carefully, but I didn't see anything that addressed the question of what phosphorylates Gpd1 or any other protein. Nor did I see anything that led me to expect to find kinase/phosphorylation data in this paper.

**Comment by ValWood** [comment]
I mean phosphatase.
It seems strange considering the title.....if they were looking for PPA2 substrates....

**Comment by Antonialock** [comment]
I had a look at it and I think the annotations look ok based on the paper.
[pmic7718.pdf](https://github.com/pombase/curation/files/697558/pmic7718.pdf)
