### ISSUE TITLE
dlp1 and dps1 involved in isoprenoid biosynthetic process?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1275]
Are pombe dlp1 and dps1 involved in isoprenoid biosynthetic process? they don’t seem to be to me?
but I’m not sure. all the pathway maps are a bit confusing
there was once a discussion about this
https://github.com/geneontology/go-annotation/issues/1461
but I never filtered the mappings and I’m not sure if I should
but it seems to be in the dolichol part of the pathway?

- [ ] if no filter mapping (manually annotate  correct ones)
- [ ] if no  report error

**Comment by Antonialock** [comment]
I think it is involved in isoprenoid metabolism? It is needed for ubiquinone biosynthesis...
Eg. coenzyme Q10 has a benzoquinone ring + 10 isoprene units in its sidechain (decaprenyl) 

The a benzoquinone ring comes from phenylalanine or tyrosine, and the isoprene units come from the mevalonate pathway

To make some isoprenoids:

![screen shot 2017-02-01 at 08 23 14](https://cloud.githubusercontent.com/assets/12727506/22499607/bcf14ab6-e857-11e6-93fb-f4cc61f6669e.png)



Now you have made some IPP...
dlp1 and dps1 ( decaprenyl diphosphate synthase) make the decaprenyl-PP by adding isopentenyl diphosphate (IPP) molecules to farnesyl diphosphate or geranylgeranyl diphosphate (also derived from mevalonate pathway) in multiple steps catalyzed by

https://www.google.com/patents/US8367395
![screen shot 2017-02-01 at 08 15 34](https://cloud.githubusercontent.com/assets/12727506/22499442/ba3778dc-e856-11e6-9da3-2f0bb46de639.png)

I say "to farnesyl diphosphate **or** geranylgeranyl diphosphate" because I also found this image so maybe different eukaryotes have a different preference (or one of the images are the wrong way around)
![screen shot 2017-02-01 at 08 38 36](https://cloud.githubusercontent.com/assets/12727506/22500044/0308eb56-e85a-11e6-8732-c63d02daafc4.png)

**Comment by Antonialock** [comment]
I think by definition you need >2 isoprene units to form an isoprenoid? Therefore, because dlp1 and dps1 add on the isoprene units I think by definition they are involved in isoprenoid biosynthesis?

**Comment by Antonialock** [comment]
So similarily, what metabolic steps does ubiquinone biosynthesis encompass? 

tyrosine -> benzoate ring +
IPP -> decaprenyl +
combining them into ubiquinone?

**Comment by ValWood** [comment]
Ubiqunone isn't an isoprenoid
This step is downstream of isoprenoid biosynthesis.

so its isoprenoid metabolism, but not isoprenoid biosynthesis?

Correct?

re ubiquninone biosynthesis, I think there are other steps downstream of  dlp1/dps1
coq3-9


If the steps from tyrosine to 4-OH benzoate are only used to synthesize ubiquinone they should be included to. But I can't locate any of these intermediates in GO, so I'm not sure which GPs they are?
Seems odd. I wonder if that is the  eukaryotic way to ubiquinone?

**Comment by ValWood** [comment]
might be a bit of  proposed engineering -link to a patent;)

FIG. 3 depicts the mevalonate isoprenoid biosynthesis pathway, which typically operates in eukaryotes, including fungi; as well as the mevalonate-independent isoprenoid biosynthesis pathway, also known as the DXP pathway, which typically operates in bacteria and in the plastids of plants and production of isoprenoid precursors.

**Comment by Antonialock** [comment]
I think it is involved in isoprenoid biosynthesis
"The chemical reactions and pathways resulting in the formation of any isoprenoid compound, isoprene (2-methylbuta-1,3-diene) or **compounds containing or derived from linked isoprene** (3-methyl-2-butenylene) residues."

it catalyses the last step in isoprenoid biosynthesis, see here
(terpenoid=isoprenoid)
http://www.genome.jp/kegg-bin/show_pathway?map00900

**Comment by Antonialock** [comment]
ubiquinone contains 10 isoprene subunits

dps1/dlp1 condense 10 isoprene subunits + farnesyl diphosphate into an isoprenoid

I'll add isoprenoid biosynthesis to the publication where I added ubiquinone biosynthesis (I'm not sure if I should remove that one....maybe it is considered upstream? 

http://www.genome.jp/kegg-bin/show_pathway?map00130

**Comment by Antonialock** [comment]
ah thought it was my session..

**Comment by ValWood** [comment]
I'll close this and leave the mapping as is...
Its not far wrong int he whole scheme of things
