### ISSUE TITLE
"affecting"? vs "affecting activity of"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1311]
Hmm, what should we be doing here?

![affecting](https://cloud.githubusercontent.com/assets/7359272/23295112/c274161e-fa66-11e6-939d-087725b384aa.jpg)

**Comment by mah11** [comment]
These are for terms in the "catalytic activity phenotype" branch, where admins can specify which enzyme is affected, which substrate is affected (if it's a gene product), or both. The assayed_enzyme extension is displayed as "affecting activity of", but we don't have anything special for assayed_substrate. So:

1. Decide what text you want displayed for an affected substrate.
2. Edit the corresponding entry in pombe-embl/supporting_files/chado-json-config.yaml.

I'm happy to do step 2 if you do step 1.

I think there will still be some older extensions that don't distinguish enzyme from substrate, because we added assayed_enzyme and assayed_substrate more recently than the generic assayed_using.

**Comment by ValWood** [comment]
Yep, I remembered this later.

I'll look a this shortly.Not today....

**Comment by mah11** [comment]
done - we've just gove with "affecting substrate"
