### ISSUE TITLE
decreased spore viability question

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1386]
I know I have asked this a few time and that the term to use is 

FYPO:0000581	decreased spore germination frequency

but the paper I am doing  has % viability of the spores. So I'm now wondering why we don't so these as  "inviable spore" with % penetrance? (which allows us to specify more accurately 
.... I was trying to capture differences ranging between 75% and  99%, which are all "high expressivity")

**Comment by mah11** [comment]
There's no reason not to use "inviable spore" + penetrance, and in fact there are more annotations to FYPO:0002151 than to FYPO:0000581.

I'm not sure whether to keep both terms or just one. It seems like we should keep FYPO:0002151 because we have more annotations and the extension can be more precise. But if we make FYPO:0000581 obsolete we won't have a "spore population" term, only the cell-level one.

**Comment by ValWood** [comment]
I guess we should keep both because that's consistent with vegetative and cell population. 

 maybe the synonym could be applied to both terms, and a comment on the population term to make the 
 "inviable spore" with penetrance if you know the % of dead spores?

**Comment by mah11** [comment]
synonym & comment added
