### ISSUE TITLE
extension options for recombination

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1388]
One of the options is gene?
(you don't really assay a gene, you assay a region?)

**Comment by ValWood** [comment]
Do you agree? I find this confusing @mah11  @Antonialock

**Comment by mah11** [comment]
Which ontology(ies)? What is/are the prompt(s)?

**Comment by ValWood** [comment]
Oh yes, there is something missing from this ticket!

It was FYPO but I can't find the exact term now.
abnormal mitotic and meiotic recombination  don't show this option in test....

 will have another look tomorrow...

**Comment by ValWood** [comment]
found this in my trash...

![recomb options](https://cloud.githubusercontent.com/assets/7359272/25251781/60d4ab8a-2612-11e7-8cfa-04f354e9a0c3.jpg)

**Comment by ValWood** [comment]
I think what alerted me to this was that assayed gene was used in one session. I changed this to M26 hotspot...

**Comment by mah11** [comment]
OK, just knowing it's FYPO helps some. The config has these for FYPO:0000063 (abnormal DNA recombination):

    FYPO:0000063    is_a    assayed_using   SO:0001411-SO:0000839   assayed region          0,1     user
    FYPO:0000063    is_a    assayed_using   GeneID  assayed gene            0,1     admin

The "gene" option is admin-only, so community users won't have any problem. I think I must have included the it for us because I saw some genes used in extensions that existed back when I reviewed them all to set up the extension config. I could envision using it to mean "assayed recombination in a region identified as being near this gene" but I wouldn't want to offer that to any old user.

That said, some of the gene extensions look like they may have been reporter genes rather than assays done in the region around the native locus (ura4, ade6).

**Comment by ValWood** [comment]
transferred comment from https://github.com/pombase/curation/issues/1343

Something seems strange about this.
I will look closer. Is it really increased recombination of ade6...? or is it at M26 site?
I'm not quite sure it captures the intended biol....

ade6
ade6-M375(G45->stop)[Not assayed]
FYPO:0003891	normal intragenic meiotic recombination	Cell growth assay	assayed_using PomBase:ade6
ade6
ade6-M26(G46->stop)[Not assayed]
FYPO:0004057	increased intragenic meiotic recombination	Cell growth assay	assayed_using PomBase:ade6

**Comment by ValWood** [comment]
transferred comment from https://github.com/pombase/curation/issues/1343

I think the affecting ade6 is confusing here (its coincident with the M26 recombination hotspot isn't it?)

there is a term
FYPO:0004059 normal meiotic recombination at M26 site
which sounds like ti would be more meaningful (although there is currently no abnormal equivalent).
I think it would be clearer for users...

**Comment by ValWood** [comment]
kepp in mind but no action right now
