### ISSUE TITLE
phosphatase activity

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1513]
shouldn't these be protein phosphatase and protein phosphatase inhibitor?
https://www.pombase.org/reference/PMID:23962284

**Comment by mah11** [comment]
This paper only uses a non-protein substrate (PNPP) in the assays that support the IDA annotations, so they're correct as they are (even though the annotated proteins probably are protein phosphatase and inhibitor in vivo).

**Comment by ValWood** [comment]
but	phosphatase inhibitor activity
has direct input  pzh1 which by definition makes it a protein phosphatase inhibitor?

maybe we  could use EXP here to capture the author intent? I didn't look at the paper, I was just assuming that is a protein substrate is captured we  could infer.....

**Comment by mah11** [comment]
Not from this paper alone, because its direct assays only show dephosphorylation of PNPP. Pzh1 is the phosphatase whose activity is inhibited, not the assayed substrate.

IOW, the assays in this paper show:
- pzh1 dephosporylates PNPP and
- hal3 inhibits pzh1's activity that dephosporylates PNPP.

To annotate to protein phosphatase and protein phosphatase inhibitor you have to add information that doesn't come from the direct assays (sequence similarity?). That could be done with IC.

**Comment by ValWood** [comment]
but we already know that pzh1 is a protein phosphastase (independently of this paper?)

so the author intention is to  show that hal3 is a protein phophastase inhibitor?

If we can describe something a s a phosphatase inhibitor acting on a protein, we must be able to make the  inference
"protein phosphatase inhibitor".

**Comment by mah11** [comment]
but we already know that pzh1 is a protein phosphastase (independently of this paper?)

Then you can make the "protein phosphatase activity" annoation for pzh1, but you cannot use this paper+IDA as the reference/evidence combination. You have to use IC evidence, because you are bringing in knowledge from outside the direct assays shown in the paper.

> so the author intention is to show that hal3 is a protein phophastase inhibitor?

Similarly, hal3 can be annotated to "protein phosphatase inhibitor activity", but not with PMID:23962284+IDA. This one also has to be IC because the assays in the paper do not show a _protein_ phosphatase reaction.

> If we can describe something a s a phosphatase inhibitor acting on a protein, we must be able to make the inference "protein phosphatase inhibitor".

I'm not sure this statement is entirely free of ambiguity (does "inhibitor acting on a protein" mean acting on the protein whose phosphatase activity is regulated, or on some protein that is being dephosporylated ... or both?), but it doesn't really matter. The assays in this paper do not show any protein being dephosphorylated - they use PNPP, not a phosphoprotein, as the assay substrate - so they do not show a protein phosphatase acting or having its activity inhibited.
