### ISSUE TITLE
cdc2 targets Nurse lab Swaffer dataset

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1516]
Matthew Swaffer's data
priority

**Comment by ValWood** [comment]
Mailed @jvhayles for Matthews forwarding e-mail

**Comment by ValWood** [comment]
Contacted Matthew.

**Comment by mah11** [comment]
The modification file is ready to roll. Before I open the chado ticket to have Kim add the GAF to "files the loader knows about", I have a couple of questions:

1. What evidence should we use for the cdc2 GO:0004674 annotations? Right now the GAF has EXP, because I wasn't sure if you wanted to count these as IDA, or be more cautious and say IMP. Or we could leave it as EXP.

2. I included happens_during(GO phase ID) extensions for the substrates that had entries in the "cell cycle dynamics" column, but it wouldn't be much trouble to remove them if you or Matthew think they're overstating the case. They are a tiny bit of a stretch given that we've gone with "present_during" rather than "added_during" for the modification annotation extensions.

files:
pombe-embl/external_data/external-go-data/PMID_27984725_gaf.tsv
pombe-embl/external_data/modification_files/PMID_27984725_modifications.tsv

**Comment by ValWood** [comment]
EXP sounds good...

I think happens_during is OK. It matches how we have been using it 
generally anyway.

Fab, thank you so much!

**Comment by mah11** [comment]
OK. The modification file has present_during(phase), based on the emails from Matthew. I thought maybe if we weren't going to use added_during there, saying happens_during for the cdc2 MF annotations didn't quite match, but I'm not that bothered if it's OK with you.

**Comment by ValWood** [comment]
Hmm, what the user sees is just "during"

I think Matthew was bothered more about the ones which had no phase listed, but which we *could infer* were definitely present during M-phase.
For the ones which are specified, I think its fine.

We can reassess if he thinks it seem's odd when live.

**Comment by mah11** [comment]
What made me unsure is that:
if Matthew prefers "present" to "added" for when they see the modification, that means they're sure the target has a phosphorylation on it in x phase. I took it to mean they're not as sure the phosphorylation is actually added right when they see it - i.e. I'm not sure they're sure they've ruled out the modification getting added earlier but only being detected later.

If they are sure about when the phosphorylation happens, I can change the modification extensions to added_during.

Again, this is me being extra fussy, so I'll just quietly think it and only bother changing the annotations if Matthew complains.

**Comment by ValWood** [comment]
Hmm, i'm not sure.

I never took the GO extension happens_during to mean this is when it was added. I thought it could also mean  this is "a time when it is present"....if we need more precision maybe we can just use "during"

**Comment by mah11** [comment]
The happens_during extension always means "when the gene product does the action described by the MF or BP term it's annotated to". The "when it is present" business works for GO CC exists_during, and for MOD present_during extensions, not for GO MF/BP happens_during.

Plain "during" is less precise than any of the *_during extension relations.

The annotations in question are to GO:0004674, protein serine/threonine kinase activity. So for these annotations, if we use compound "happens_during(x phase), has_direct_input(gp)" we're saying cdc2 has kinase activity that acts on substrate gp in x phase.

**Comment by ValWood** [comment]
So in this case  it won't make sense to say
happens during (mitotic S-phase), happens during (mitotic G2 phase),  happens during (mitotic M-phase), if the phospho site is added in S-phase and stays there.

However the phosphorylation is going to be happening *continually* to maintain it throughout these phases  ( after all it's just a balance between the kinase adding faster than  the phosphatases  are removing), so in this case it might be fine. To *maintain* the phosphorylation it must still be *happening*, otherwise the phosphorylation would quickly disappear during these phases.

I have convinced myself that happens_during is OK

Are we overthinking this?

**Comment by mah11** [comment]
> Are we overthinking this?

Probably!

I'll stick with my "see if Matthew squawks" approach for now.
