### ISSUE TITLE
PMID:1645660 pho2 4-nitrophenol catabolic process

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1528]
Is that physiological? Abstract says nothing known about physiological role?

**Comment by Antonialock** [comment]
no that was an overstatement

also about the assay substrate
"This assay is widely used for detection of alkaline phosphatase activity in ELISA, but can be used in many instances where protein phosphatases are assayed. Because both acid and alkaline phosphatases act on pNPP..."

so I'll move the MF up to phosphatase activity
