### ISSUE TITLE
vip1 name query

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1562]
De anyone know where this name came from? It isn't published as vip1 as far as I can tell, and it has no named/identifiabe orthologs

SPAC10F6.06	RNA-binding protein Vip1

Also this rather confusing statement on the InterPRO family:

http://www.ebi.ac.uk/interpro/entry/IPR034358

It is worth noting that the Vip1 mentioned in this entry is SPAC10F6.06. Another S. pombe protein, Vip1 (SPCC1672.06c), is not in this entry.

I'm wondering if this should have vip1?

- [ ]  when resolved whatever the outcome suggest clarification for the statement on the InterPro family

**Comment by mah11** [comment]
ooh, fun with detective work!

- asp1/SPCC1672.06c has vip1 as a synonym.

- Papers seem to use asp1 as the name for SPCC1672.06c, e.g. PMID:20624911, PMID:25254656.

- The supplemental tables for PMID:25375137 list vip1 as the name for SPAC10F6.06, but don't say where they got the name.

- PMID:24382491 says that translin interacts with a "vip1" that has an RNA recognition motif (RRM). They give no indication what gene it is (no systematic ID, no sequence, nada), but my guess is that it is SPAC10F6.06 because the protein features on the PomBase gene page include an RRM, and there isn't one for asp1/SPCC1672.06c.

Based on the above, I think it might cause less upheaval to keep the standard names as they are, and have InterPro clarify their note to "Note that the Vip1 mentioned in this entry is SPAC10F6.06. Another S. pombe protein, Asp1 (SPCC1672.06c), has Vip1 as a synonym but is not in this entry.".

**Comment by mah11** [comment]
Now I've traced the vip1 name for SPAC10F6.06 to this, which doesn't seem to be in PubMed, and which cites two references, one of which is a PhD thesis, and both of which are in German. It does at least show a peptide sequence that matches SPAC10F6.06.

http://www.sciencedirect.com/science/article/pii/S1631074809001507

**Comment by ValWood** [comment]
Wow thank you!

**Comment by mah11** [comment]
I haven't actually figured out how we (read: you) got hold of the vip1 name to put it in GeneDB or PomBase, though!

**Comment by ValWood** [comment]
OK, A thourough search of my e-mail archive turned up nothing useful. It did drag up a few old "Milly Boon's" which I managed to avoid looking at...
I'll close and ask InterPro to update the family info.

**Comment by ValWood** [comment]
I think  it might come from here
http://www.ebi.ac.uk/ena/data/view/Y13635 (tabby tabby tabby b***cks view grrh)

 after clicking on all, under publications I found
[1]
A p53-related protein from fission yeast

 a bit of wishful thinking there ;)
