### ISSUE TITLE
pek1   function process links

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1606]
- [ ] GO:0043406 | positive regulation of MAP kinase activity
-- | --

not  required

-protein tyrosine kinase activity   | has substrate pmk1

(will block this term)

als needs F-P link

**Comment by ValWood** [comment]
we are not capturing the essence of this paper:
http://pombase2.aska.gen.nz/reference/PMID%3A10365961

The mitogen-activated protein kinase (MAPK) pathway is a highly conserved eukaryotic signalling cascade that converts extracellular signals into various outputs, such as cell growth and differentiation. MAPK is phosphorylated and activated by a specific MAPK kinase (MAPKK): MAPKK is therefore considered to be an activating regulator of MAPK. Pmk1 is a MAPK that regulates cell integrity and which, with calcineurin phosphatase, antagonizes chloride homeostasis in fission yeast. We have now identified Pek1, a MAPKK for Pmk1 MAPK. We show here that Pek1, in its unphosphorylated form, acts as a potent negative regulator of Pmk1 MAPK signalling. Mkh1, an upstream MAPKK kinase (MAPKKK), converts Pek1 from being an inhibitor to an activator. Our results indicate that Pek1 has a dual stimulatory and inhibitory function which depends on its phosphorylation state. This switch-like mechanism could contribute to the all-or-none physiological response mediated by the MAPK signalling pathway.

- [ ] Need IDs for phosphorylated form and phosphorylated form of pek1
to show that unphosphorylated form as an inhibitor of pmk1

- [ ]  I deleted the 'redundant'  protein tyrosine kinase activity
but  if this is shown here  there should be a modified residue annotation for pmk1 from this paper?

**Comment by ValWood** [comment]
not super urgent

**Comment by Antonialock** [comment]
I'm not sure I would annotate the inhibitory 'function' - I'd assume that it is due to disrupting the normal balance of components in the cascade (i'm not sure but I guess they are scaffolded - so when you overexpress the MAPK then maybe some are just floating around and being activated by a random player if that makes sense?)

Found the phosphorylated residue in the methods section :-)
"phospho-Pmk1 antibodies were prepared by immunizing rabbits with a synthetic phosphopeptide (ENPGFMpTEpYVATRWY: amino acids 180 to 194 of Pmk1)"
