### ISSUE TITLE
	GO:0030819	 positive regulation of cAMP biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1610]
I don't think we should really use this term. The pathway isn't "synthesising cAMP" it is just isomerising  AMP?

It isn't metabolism as such. I don't know how to explain it but I opened a ticket...

https://github.com/geneontology/go-ontology/issues/13910

**Comment by ValWood** [comment]
@Antonialock  what do you think?

**Comment by Antonialock** [comment]
well, it is definitely not isomerization (Triphosphate -> Monophosphate) 

I think it is metabolism? I guess it is different from what you classically think of as metabolism since it is metabolism of a cellular signal rather than a substance needed for "housekeeping"?

Do you think that PLC metabolises PIP2 or not?

**Comment by ValWood** [comment]
> well, it is definitely not isomerization (Triphosphate -> Monophosphate)

oh yeah.
there was a lot of discussion in GO about  whether these sorts of things  should be considered catabolism/biosynthesis, if that is not the purpose of the pathway.

This might not be one of them.
Anyway, so if this annotation is valid (which it seems to be), I think the annotation should be implicit from the eventual MF annotation, which should be something like

"adenylate cyclase activator activity"
and would have a parent to  "GO:0030819	positive regulation of cAMP biosynthetic process"
