### ISSUE TITLE
zwf1 FYPO to filter? (deletion project)

### ISSUE THREAD

**Issue by mah11** [pombase/curation#1660]
PMID:28667014 (recently community curated) has small-scale data showing that a zwf1 deletion is viable. 

- Should we filter the FYPO:0002061 annotations from the big deletion project papers?

- If yes, what do we actually do (where does filtered-htp-FYPO info live)? I'm happy to do it once I know how ...

**Comment by ValWood** [comment]
@ JackyVH  do you agree? I have only "blocked" a couple so far.... when we have been certain

I'll take this one (its slightly complicated because I have kept it fo now so that I can regenerate phenotypes from the original spreadsheet..  I planned to make the PHAF itself the editable thing at some point, but I still need to deal with the "sporulation phenotypes" problem.

**Comment by ValWood** [comment]
@ JackyVH should we block this in the deletion collection annotation, or do you know of any reason that it could be  different?

**Comment by ValWood** [comment]
For now we are leaving both.
