### ISSUE TITLE
checkpoint signalling checks...

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1727]
- [x] As mentioned above, when DNA replication is perturbed by HU, two TQ motifs in Mrc1 are phosphorylated by Rad3 for checkpoint signaling to Cds1. Once phosphorylated, the two TQ motifs function redundantly in recruiting Cds1 to be phosphorylated by Rad3 (15).

15. Xu YJ, Davenport M, Kelly TJ. Genes Dev. 2006; 20:990–1003. [PubMed: 16618806]

This is captured

**Comment by ValWood** [comment]
Under HU-induced replication stress, Thr412 in the C-terminus of Rad9 in 9-1-1 complex is also phosphorylated by Rad3 (40)
40. Furuya K, Poitelea M, Guo L, Caspari T, Carr AM. Genes Dev. 2004; 18:1154–1164. [PubMed: 15155581]

**Comment by ValWood** [comment]
In S. pombe, the major mediator of the replication checkpoint Cds1 is activated by a two- stage mechanism (13,15,41). In the first stage, Cds1 is recruited by phosphorylated Mrc1 to be phosphorylated by Rad3 at Thr11 residue. In the second stage, phosphorylated Cds1- Thr11 promotes homodimerization of two inactive Cds1 molecules, which facilitates the autophosphorylation of Thr328 in the activation loop of the kinase domain. Phosphorylation of Thr328, which is suppressed by autoinhibitory C-terminus under normal conditions, directly activates Cds1. Because phosphorylation of Cds1-Thr11 by Rad3 primes autoactivation of the kinase, it has been used as a reliable marker for Cds1 activation (41,42)



41. Yue M, Singh A, Wang Z, Xu YJ. J Biol Chem. 2011; 286:22864–22874. [PubMed: 21561865]
42. Tanaka K, Boddy MN, Chen XB, McGowan CH, Russell P. Mol Cell Biol. 2001; 21:3398–3404. [PubMed: 11313465]

**Comment by ValWood** [comment]
All of these phosphorylation event  connections are now in place , just need  rad3->rad9 from the  old Carr lab paper

**Comment by mah11** [comment]
What is the task here?

**Comment by ValWood** [comment]
Just this paper left, to get the rad3-rad9 connection

 - [ ] Under HU-induced replication stress, Thr412 in the C-terminus of Rad9 in 9-1-1 complex is also phosphorylated by Rad3 (40)
40. Furuya K, Poitelea M, Guo L, Caspari T, Carr AM. Genes Dev. 2004; 18:1154–1164. [PubMed: 15155581]

rad3-> rad9 is missing

**Comment by mah11** [comment]
I've left the session in approval - I would like you to double-check what I've annotated for kinase activities, modifications, and phosphorylation phenotypes, because I'm not sure I've got it right. The text passages for Fig 2 are badly written and got me confused, and I'm not sure how much can be curated from Fig 4 because most of the panels don't include wild type ("wt" only refers to the rad4/cut5 allele). Finally, also not sure whether to annotate anything from Fig 6 because they only look at mobility shift (or lack thereof in rad9-T412A) for Crb2 and Rad4 ... it's almost certainly phosphorylation but it's just not explicitly shown here.

**Comment by ValWood** [comment]
OK I'll take a look.

**Comment by ValWood** [comment]
I think this all looks fine.

The only thing I wondered about  was "response to hydroxyurea"

I  thought we did not use this in GO annotation since its only a condition to induce DNA damage.

But I can see why you have because there is no way to distinguish UV-induced damage from nucleotide availability induced damage (HU targets ribonucleotide-reductase ?)

**Comment by mah11** [comment]
> The only thing I wondered about was "response to hydroxyurea"
> 
> I thought we did not use this in GO annotation since it's only a condition to induce DNA damage.
> 
> But I can see why you have because there is no way to distinguish UV-induced damage from nucleotide availability induced damage (HU targets ribonucleotide-reductase ?)

It's not even damage; HU does inhibit ribonucleotide reductase, and that slows replication, but does not necessarily damage DNA.

Someday maybe there will be a way to convert that extension to refer to exposure rather than a possibly-spurious response, but it won't happen soon enough to be worth leaving this ticket open to wait for it!
