### ISSUE TITLE
Query EC mappings ynd1

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1739]
https://www.pombase.org/gene/SPCC11E10.05c

**Comment by ValWood** [comment]
@Antonialock  @mah11 
does this bunch of MF mappings seem correct to you.
(I don't know what dATP is...)

**Comment by mah11** [comment]
These annotations are logical consequences of connecting EC:3.6.1.5 to ynd1 - all of those MF terms do have that EC number as an xref. That, in turn, is because of how that EC entry is defined - it describes activities that "apyrase" enzymes have, rather than representing what GO MF would call a single catalytic activity.

> (I don't know what dATP is...)

yes you do - it's the "A" that gets incorporated into DNA

**Comment by ValWood** [comment]
Oh dear! back to biochemistry school!

So the EC GO mapping is wrong?

**Comment by ValWood** [comment]
removed....this is an ER enzyme
