### ISSUE TITLE
what is abnormal about the cell cycle regulation?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1746]
https://www.pombase.org/reference/PMID:1549179

(is it a transition block, if so which?)

**Comment by mah11** [comment]
This paper is from 25 years ago, and the experiments aren't precise enough to show anything more specific than that in some mutants cell division is delayed (and then resumes) upon cell annoyance. The world has since learned about the checkpoints invoked upon ionizing radiation, and which transitions they regulate, but the data ain't in this one.
