### ISSUE TITLE
revise conjugation with cellular fusion annotation

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#1942]
need to draw the main pathways out on paper, make sure that gp's are annotated as specifically as possible, and get rid of redundant/confusing GO terms.

https://github.com/geneontology/go-ontology/issues/15337

**Comment by ValWood** [comment]
from 
mei2 should be able to say has substrate mei2 during induction of conjugation etc
https://github.com/pombase/curation/issues/1658

**Comment by ValWood** [comment]
fus1

antonia
needs agglutination
Petersen J, Weilguny D, Egel R, Nielsen O: Characterization of fus1 of Schizosaccharomyces pombe — a developmentally controlled function needed for conjugation. Mol Cell Biol 1995, 15:3697-3707

fus1.B20 cells, which halt sexual differentiation after cell-to-cell contact and agglutination but before cell wall fusion

val
How is it involved in agglutination, agglutination is caused by adhesion molecules on the cell surface. How is the actin cytoskeleton connected to agglutination?

from
https://github.com/pombase/curation/issues/2035

**Comment by ValWood** [comment]
cell morphogenesis involved in conjugation with cellular fusion
should be more specific

**Comment by ValWood** [comment]
will be done in time....
