### ISSUE TITLE
check out "abnormal segregation in meiosis I, split kinetochore, normal separation"

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#1982]
I can't figure
abnormal segregation in meiosis I, split kinetochore, normal separation, because  split kinetochore is usually cohesin abolished  (which is abnormal separation), but could segregate normally? 

![do these make sense](https://user-images.githubusercontent.com/7359272/39329302-caf53154-4995-11e8-84d4-6fe03236941f.jpg)

**Comment by mah11** [comment]
well, you requested both terms in https://github.com/pombase/fypo/issues/2782
maybe the discussion in that ticket will help

**Comment by ValWood** [comment]
OK I'll take this and refresh n the difference...

**Comment by ValWood** [comment]
OK, this may just be me.

I think it seems odd because I wouldn't use the phrase "equational separation" I would only use
"equational segregation" . But this is because I think of separation as only the part of chromosome segregation where the chromosomes are detached from one another, which fits the GO def.

I realise that segregation is broader and includes things both before and after separation. 
the part that is normal is the 
GO:0051305    chromosome movement towards spindle pole

thoughts?

**Comment by ValWood** [comment]
...So maybe the terms would be clearer is called something like

split kinetochore in meiosis I with  normal homologous chromosome segregation

split kinetochore in meiosis I with  equational sister chromatid segregation

(both would be descendants of abnormal chromosome segregation in meiosis I, but that might be confusing in the term names)

**Comment by mah11** [comment]
I've only had a quick look over the FYPO tickets, so I probably don't have the whole story back in my head, but the tickets do explain my reasoning for the current term names.

- I used "separation" instead of "segregation" as the last word in both term names because of the separation-part_of-segregation angle, and because in both cases there's something abnormal about the overall segregation process. In one case the separation is normal, in the other it's not, but in both one (or more) earlier steps isn't normal. It would also look a bit odd to say "segregation" twice in one term name.

- The terms combine structural (split kinetochore) and process (segregation, separation) information but mainly describe processes that show varying degrees of abnormality. I've already said (in #2794) that I'm not keen on naming process phenotypes too much like structural phenotypes, and that's why I haven't jumped to put "split kinetochore" at the start of the FYPO:0005633 and FYPO:0005634 names.

As a result of looking at this again I'm now a bit worried about whether FYPO:0005633 and FYPO:0005634 actually use "split kinetochore" the way it's defined in the rest of FYPO, i.e. to mean that one kinetochore has broken into parts.

In meiosis I the kinetochores of both copies of one replicated chromosome stay together. If each kinetochore is intact, but they dissociate from one another when they shouldn't, that _doesn't_ fit FYPO's generic definition of "split" and we should use a different word in these term names. If that's the case, that could get us around my structure/process concern, though - I could rustle up something like "sister kinetochore separation during meiosis I" to use in the names.

**Comment by mah11** [comment]
OK, opened a FYPO ticket

**Comment by ValWood** [comment]
I think this is OK. Easier to assess next time I'm annotating one of these
