### ISSUE TITLE
mitochondrial disorders?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2047]
shouldn't these have?
paraganglioma
pheochromocytoma

**Comment by ValWood** [comment]
how is mitochondrial disorder defined?

is it a specific type of disease?

@Antonialock

**Comment by Antonialock** [comment]
from wikipedia
itochondrial diseases are a group of disorders caused by dysfunctional mitochondria, the organelles that generate energy for the cell. Mitochondria are found in every cell of the human body except red blood cells, and convert the energy of food molecules into the ATP that powers most cell functions.

Mitochondrial diseases are sometimes (about 15% of the time)[1] caused by mutations in the mitochondrial DNA that affect mitochondrial function. Other mitochondrial diseases are caused by mutations in genes of the nuclear DNA, whose gene products are imported into the mitochondria (mitochondrial proteins) as well as acquired mitochondrial conditions. Mitochondrial diseases take on unique characteristics both because of the way the diseases are often inherited and because mitochondria are so critical to cell function. The subclass of these diseases that have neuromuscular disease symptoms are often called a mitochondrial myopathy.

**Comment by ValWood** [comment]
So it's any disorder caused by a protein that resides in the mitochondria?

(we only have a small subset annotated, if so)

**Comment by mah11** [comment]
I would say it's any disorder in which mitochondrial function goes awry; that seems consistent with the blurb Antonia pasted. I imagine there's a lot of overlap between "proteins where mutations cause mitochondrial disorders" and "proteins that normally reside in mitochondria" but I don't know for sure that there are no exceptions.

**Comment by Antonialock** [comment]
yeah I'll add it...plus a few stragglers that should also have the annotation

**Comment by ValWood** [comment]
I did a query  for mitochondrial proteins intersected with  disease genes and then subtracted those with "mitochondrial disorder".

There were a lot left...

**Comment by ValWood** [comment]
I think we are safe to call anything which affects the respiratory chain a mitochondrial disorder....

**Comment by Antonialock** [comment]
yes of course.

What I meant was that I don't know if mitochondrial dysfunction is the only reason patients develop paragangliomas or pheochromocytomas

**Comment by Antonialock** [comment]
but I updated so that sdh1 sdh2 sdh3 tim18 and emi5 all have annotations to mitochondrial disorder, paraganglioma, pheochromocytoma, and cancer

**Comment by Antonialock** [comment]
> I did a query for mitochondrial proteins intersected with disease genes and then subtracted those with "mitochondrial disorder".

Doesn't surprise me...these came out of a student project back from when we wereon less than frequent updates...I can put it on my list but I have some other tasks I really feel I should be getting on with!

**Comment by ValWood** [comment]
well I guess it will be superseded by
https://github.com/pombase/curation/issues/49
so closing
