### ISSUE TITLE
atn1 product does not make sense

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2104]
mitochondrial iron-sulfur cluster assembly exporter Atm1

what is being transported?

just iron, or the entire "cluster"
?

http://pombase-dev.bioinformatics.nz/gene/SPAC15A10.01

**Comment by ValWood** [comment]
This should also be reflected in the process/substrate transport annotation

**Comment by Antonialock** [comment]
changed to mitochondrial iron-sulfur cluster exporter Atm1

I'm reluctant to annotate to iron-sulfur cluster transport (or a not-yet-existing descendant e.g. iron-sulfur cluster export from mitochondrion) because the exact product transported is unknown, see https://www.sciencedirect.com/science/article/pii/S0171933515000485

**Comment by ValWood** [comment]
"exporter" implies it is a "transporter" of "iron-sulfur cluster"

maybe we should call it
mitochondrial iron-sulfur cluster assembly protein?

**Comment by Antonialock** [comment]
I don't think that describes it.

It is a transporter, presumably transporting a molecule that is bound to an iron sulfur cluster (e.g. a protein or GSSG...or something). But it's not been shown exactly what it transports. 

It is needed for cytosolic iron sulfur cluster assembly

**Comment by ValWood** [comment]
Ok then your product makes sense!
