### ISSUE TITLE
quiescence in GO, a question

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2170]
https://www.ebi.ac.uk/QuickGO/term/GO:0044838

is described a phase in GO.

However, it could be described also as a process (a bit like mitotic cell cycle phase vs mitotic cell cycle)

quiescence is characterised by a set of genomic and metabolic changes which we will increasingly need to annotate. I can't see where we would annotate these at present?

**Comment by ValWood** [comment]
Related, these seem like phenotypes (prevent G0 exist, but may just be some upstream block, rather than regulation?)

![odd annotations](https://user-images.githubusercontent.com/7359272/44718045-bad39b80-aab6-11e8-846b-fd1fed78206b.jpg)

**Comment by ValWood** [comment]
...are probably OK, but dom34 looked odd (translation). MAybe it is OK

**Comment by mah11** [comment]
> However, it could be described also as a process (a bit like mitotic cell cycle phase vs mitotic cell cycle)

I disagree, unless I've misunderstood what you mean. I think GO is correct to have cell quiescence as a phase. The processes would be entering or exiting quiescence, analogous to the cell cycle phase transitions.

> quiescence is characterised by a set of genomic and metabolic changes which we will increasingly need to annotate.

The changes can be described as parts of the transitions to or from quiescence; it may need new terms. Anything that happens during the quiescence phase itself (rather than during a transition) can use the "normal" GO term plus a during GO:0044838 extension.

**Comment by ValWood** [comment]
I don't need this right now, but my understanding is that there is quite a lot going on *during quiescence*. The cells aren't metabolically inert, there still seems to be turnover. However I might be wrong, and the things I was bothered about for now are sorted so closing.....
