### ISSUE TITLE
Transcription factors/ extensions

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#22]
tidy pap1  and other major TF as discussed at curator meeting

i) promoter only onDNA binding, 
ii) regulation targets on TF MF term (it has the promoter and txn regulated). 
Always represent on MF if possible

Remove redundent process annotation
Move targets onto MF where possible

Document targets/extensiosn which should be made preferentiall on MF

Original comment by: ValWood

**Comment by ValWood** [comment]
- [] prz1
moc3
yox1
atf21
rst2
mat3-Mc
sep1
cuf2
sak1
mbx2
loz1
cha4
cbf12
ams2
sre2
map1
php4
res2
atf31
mbx1
rsv1
gsf1
toe1
php3
ste11
phx1
fkh2
ace2
gaf1
fhl1
prt1
php2
mei4
atf1
sre1
mat1-Mc
klf1
rrn7
cbf11
rsv2
thi5
hsr1
grt1
pap1
toe3
thi1
res1
prr1
scr1
pcr1
cdc10
hsf1
rep1
rap1
php5
cuf1
fep1
toe2
esc1
deb1
zip1

**Comment by ValWood** [comment]
I'm handing this one over to you to make sure we are on the same page for TF annotation. Just ask if any of my comments don't make sense.

All DNA binding TFs should have two terms
i) a DNA binding term. This is where the motif goes in the extension
ii) a transcription factor activity term (I know, this is really a process, "regulation of transcription", in the function ontology, which is why it is confusing)> this is where we put the regulation targets. This is the only place where we use 'regulates" on a MF term instead of has_substrate...which confirms that its really a process, but hey ho....

**Comment by ValWood** [comment]
I put this at low priority, we can fix things as we see them and check again in about 12 months.
Not high enough priority for users or us for a directed effort.

**Comment by ValWood** [comment]
OK I pulled out the ones where I think we know the TFs are regulating the GPs directly (and we know the binding element, so can confirm, should show up in the Ensembl track)
