### ISSUE TITLE
using replication as a network example

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2213]
A few  likely missing things

- [x] orc1 has no annotation to replication initiation
- [x] cdc23 has no annotation to replication initiation
- [x]  dpb3 has no annotation to initiation but the other members have (is this really initiation or is it elongation?)

- [ ]  cdc18 has no  MF connection to mcm loader (substrate or binding)

- [ ]  cdt1 has no interactions so it isn't in the network (physical interaction with mcm?)

- [x] rad3 has no rad26 binding, but assume this must be available based on the titles of

A kinase-independent role for the Rad3(ATR)-Rad26(ATRIP) complex in the recruitment of Tel1(ATM) to telomeres in fission yeast.

Cdc18 enforces long-term maintenance of the S phase checkpoint by anchoring the Rad3-Rad26 complex to chromatin.

- [x] crb3 appears in the network but has no annotation to DNA replication @ValWood  to work out why...

**Comment by ValWood** [comment]
crb1 does appear to be initiation, although there is only one paper...
https://github.com/geneontology/go-annotation/issues/2118

**Comment by mah11** [comment]
> orc1 has no annotation to replication initiation

added IC, like other orc subunits

> cdc23 has no annotation to replication initiation

added ISO with S.c. MCM10

> dpb3 has no annotation to initiation but the other members have (is this really initiation or is it elongation?)

For other pol epsilon subunits, it seems to be legitimately how people were interpreting phenotypes at the time(s) the cited papers were published. I'll investigate whether that's still current thinking (could be - e.g. https://www.sciencedirect.com/science/article/pii/S0960982213002741) and update accordingly.

> cdc18 has no MF connection to mcm loader (substrate or binding)

"MCM loader" isn't a GO MF, and I'm deleting the "clamp loader" annotation (it's an ISO to S.c. CDC6, which rightly doesn't have that annotation; the MCM complex is not a sliding clamp).

It wouldn't be a surprise at all if pombe cdc18 interacts with one or more MCM subunits, but we/biogrid don't have any interactions with mcm* curated. There are about a dozen cdc18 papers yet to curate (plus 5 assigned to the community), so maybe we'll get interactions from some of them. Otherwise, it may come down to what we can infer from orthologs (GO will be awkward about using anything other than IPI for a protein binding annotation).

It might take a little more digging to find out whether there should be an MCM loader MF term, and if so, to define it. PMID:28191893 looks interesting (tho we'd still have the problem of inferred-from-ortholog binding annotation).

> cdt1 has no interactions so it isn't in the network (physical interaction with mcm?)

cdt1 has genetic and physical (biogrid) annotations curated. I suppose you could see whether you think any of the physical interactions could also be done as GO protein binding - two or three of them might be no worse than GO protein binding inherently is.

> rad3 has no rad26 binding, but assume this must be available

I'll curate PMID:10559981; that will take care of it.

**Comment by ValWood** [comment]
Great. It's a really good network anyway, especially when I laid it out sensibly....

![replication](https://user-images.githubusercontent.com/7359272/47112427-30095480-d24e-11e8-954f-dd75cc396cc5.jpg)

**Comment by ValWood** [comment]
since this  PMID:22718908, Is 2013, and although I assigned to the author I never sent the session out. So I am going to delete the session, since it's too old to send out now. It's yours for some future day....

**Comment by mah11** [comment]
lucky me!

**Comment by mah11** [comment]
more on cdc18 ...

I'm coming round to the notion that MCM loading is more like a process than a function, as GO distinguishes them. Although it's not totally dissimilar to clamp loading, MCM loading involves more than one protein - ORC and Cdt1 appear to be involved, as well as Cdc6/Cdc18 - and several steps via several intermediate complexes. I'll try to craft a BP term & def for the short term, but GO probably ought to do a mini-project on updating BP terms for replication initiation, and the various complex assembly and remodeling events therein. 

I'll also still have to see what data I can use from pombe versus ISO or IC to actually annotate the proteins involved ... fun times.

**Comment by ValWood** [comment]
I think this can close...
