### ISSUE TITLE
in GO database

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2233]
These 4 identifiers were found to be unannotated: SPBC947.09 SPAC11D3.13 SPAC2E12.03c SPCC777.04

no idea why... they *weren't* unnanotated...

**Comment by ValWood** [comment]
one of us, no hurry

**Comment by mah11** [comment]
None of these have any experimental annotation. Each has one or two IBA annotations that we put in our GAF, and that get stripped out when we send the GAF to GO, because (as I understand it) The Pipeline has a different route for incorporating them.

AmiGO finds SPAC2E12.03c and SPCC777.04, and has the PomBase and IBA annotations; IBAs attributed to GO_Central.

AmiGO doesn't find anything for SPBC947.09 or SPAC11D3.13, and I can't see why. Not only should they get the IBAs via the pipeline, PomBase has HDAs and a couple other things. It's not clear at all why those aren't showing up.

**Comment by ValWood** [comment]
OK, we don't really 'put' then in our gaf, but they come through from GOA because of F-P links.
I will see if I can hard code them, which will over-write the IBA....

**Comment by ValWood** [comment]
SPAC2E12.03c
already had
/GO="aspect=P; term=amino acid transmembrane transport; GOid=GO:0003333; evidence=ISO; db_xref=GO_REF:0000024; with=UniProtKB:Q6ZP29; date=20150501"

maybe we are giving PAINT higher precedence than ISO, or because the  ISO is more specific this is getting dropped.
This is a problem because some PAINT inferences  are too specific.
Probably this can only be fixed by PAINT fixing the inferences. I'll open a ticket for this.

I'm going to see if a hard filter of  PTN000415968  brings our annotation back.
