### ISSUE TITLE
replication annotations not connected to the network

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2292]
I think it might be possible to connect at least some of these:

- [ ]  bur6 | SPAC17G8.03c | DNA polymerase epsilon interactor Dpb3-like
- [x]  cdt1 | SPBC428.18 | replication licensing factor Cdt1
- [ ]  chl1 | SPAC3G6.11 | ATP-dependent DNA helicase Chl1 (predicted)
- [ ]  ctp1 | SPCC338.08 | CtIP-related endonuclease
- [ ]  exo1 | SPBC29A10.05 | exonuclease I Exo1
- [ ]  fml2 | SPAC20H4.04 | ATP-dependent 3' to 5' DNA helicase (predicted)
- [ ]  kin17 | SPBC365.09c | human KIN ortholog (predicted)
- [ ]  mcb1 | SPAC1687.04 | MCM binding protein homolog Mcb1
- [ ]  msh3 | SPAC8F11.03 | MutS protein homolog 3
- [ ]  pfh1 | SPBC887.14c | 5' to 3' DNA helicase Pif1/Pfh1
- [ ]  pol4 | SPAC2F7.06c | DNA polymerase X family
- [ ]  rem1 | SPBC16E9.17c | meiosis-specific cyclin Rem1
- [ ]  rnh1 | SPBC336.06c | ribonuclease H Rnh1 (predicted)
- [ ]  rrp1 | SPAC17A2.12 | ATP-dependent DNA helicase/ ubiquitin-protein ligase E3 (predicted)
- [ ]  rtf1 | SPAC22F8.07c | replication termination factor Rtf1
- [ ]  rtf2 | SPAC1D4.09c | replication termination factor Rtf2

**Comment by ValWood** [comment]
Connection will happen if either
i) physical interaction ii) complex annotation iii) target substrate connection

**Comment by mah11** [comment]
Of these, mcb1 is the only one that looks promising .. maybe also cdt1. Details to follow.

**Comment by mah11** [comment]
> bur6

The replication annotation comes from PMID:15388803 by IMP, but the curated phenotypes aren't replication-specific. There are also physical interactions with two pol epsilon subunits, both co-IPs tested in only one direction. Don't know if you want to add GO:0005515 based on that. Note that the paper calls it dpb3, but it's not the "real" pol epsilon subunit dpb3/SPCC16C4.22 (it's got a warning and everything).

https://curation.pombase.org/pombe/curs/08dc04f357b0310b/ro/

> cdt1

cdt1 has interactions annotated; in https://github.com/pombase/curation/issues/2213#issuecomment-430679175 I sort of asked your advice on whether any should be duplicated by GO:0005515 annotation, because each is done by only one method (also see #1281, tho we've punted that stuff for now).

> chl1

The only connection to replication is via regulation of fidelity (GO:0045005), which is the one bit of replication that does overlap with repair, and chl1 is only linked to that by a genetic interaction and double mutant phenotype(s) with swi1. I don't think it's a problem that it's not in your replication network.

> ctp1
> exo1
> rrp1

These are involved in repair, and I wouldn't expect to see them in a network describing replication. They only inherit replication GO annotation via the paths involving GO:0045005 (it contributes to the repair-ish aspects of fork processing).

> fml2

This has Okazaki fragment processing by ISO from S.c., which in turn is by IGI. It doesn't look dodgy enough to delete, but it also doesn't offer any additional specificity to get it into the network.

> kin17

Replication is ISS to a human gene; no molecular data from pombe.

> mcb1

Should I steal PMID:23322785 from the assigned community curator? It has mcb1-mcm* interactions done in multiple experiments, so duplicating them with GO:0005515 annotations wouldn't be outrageous.

also see #785 and #1278 (comments starting with https://github.com/pombase/curation/issues/1278#issuecomment-277294322)

> msh3

This gets replication via GO:0061500 ancestry. I don't know the pombe mating-type gene conversion process well enough to say whether the parentage is OK (maybe @Antonialock  can look?) but it makes sense to me not to have it in a replication network.

> pfh1

This has oodles of physical interactions, many with proteins involved in replication, but the only one that isn't from one big mass spec experiment (PMID:27611590) is a two-hybrid result. Would you make GO:0005515 annotations from any of that? No data to say whether Pfh1 is in any complex. It's a helicase, so its substrate is DNA.

> pol4

Involved in repair. I suspect the replication annotation is an error. To do: recurate PMID:16120966

> rem1

Replication annotation comes from a paper not yet curated in Canto (PMID:16024772). A quick glance suggests that the annotation will go when the paper is done - rem1 cig2 double mutant "blocked before premeiotic S phase", which isn't all that specific.

> rnh1

Another one that inherits replication via regulation of fidelity (GO:0045005), and this one's only a TAS from a paper on the human ortholog. Not network fodder.

> rtf1
> rtf2

These are annotated to GO:0071171 ! site-specific DNA replication termination at RTS1 barrier, which (as the name implies) specifically refers to termination of replication in one direction at the mating-type locus barrier, not global termination. That make me think it's not a huge loss not to have them in the general replication network .. which is just as well because the annotations are based on phenotypes that are specific enough for the GO term but not to provide network-supporting bits.

There is a physical interaction between rtf2 and pcn1 from PMID:19416828, though.

**Comment by ValWood** [comment]
> There is a physical interaction between rtf2 and pcn1 from PMID:19416828, though.

OK I'll figure out why that isn't showing...

**Comment by ValWood** [comment]
> bur6

yes I remember this was a mess. Do you think "DNA replication" annotation should be removed. I'm sure there was a later paper though....

**Comment by ValWood** [comment]
> cdt1

I think we know enough to make a GO IPI to  Mcm or orc

although it should be included via 

GO:0005656 | nuclear pre-replicative complex

I'll look into that too.

**Comment by ValWood** [comment]
> Should I steal PMID:23322785 from the assigned community curator? 

nah, i'll send a reminder.  They usually do them.

**Comment by ValWood** [comment]
> re
GO:0005656 | nuclear pre-replicative complex
I'll look into that too.

I excluded it.  I will un-exclude it

**Comment by ValWood** [comment]
> There is a physical interaction between rtf2 and pcn1 from PMID:19416828, though.

Ah I see that isn't curated yet. That will come along soon then.

**Comment by ValWood** [comment]
We can leave bur6. I might ask Stuart McNeil... I think the Durso paper should probably be retacted ;) I won't use the genetic interactions as they could be indirect.

In fact, based on the fact that S. cerevise bur6 is not related to replication, I think we should probably delete all annotation to replication and ISS to SGD
regulation of transcription by RNA polymerase II 
https://www.yeastgenome.org/locus/YER159C#go

**Comment by mah11** [comment]
OK. Do you want to do that (since you did the existing PMID:15388803 curation)?

**Comment by mah11** [comment]
> > .. inherit replication GO annotation via the paths involving GO:0045005 (it contributes to the repair-ish aspects of fork processing)
> 
> Is this a TPV then?

Good question. I understand replication initiation better than the subsequent events, but the existing arrangement hasn't rung alarm bells for me. It still wouldn't bother me to leave it as is, because this really is a case of biologically relevant overlap between replication and repair - a bit of repair gets deployed to keep replication accurate, but the gene products that are primarily doing repair don't need to get dragged into a network that otherwise depicts the replication-specific interactions.

Does that make sense?

**Comment by ValWood** [comment]
bur6 now:

/product=" transcription regulator complex subunit Bur6 (predicted)"
/GO="aspect=P; term=regulation of transcription by RNA polymerase II; GOid=GO:0006357; evidence=ISS; db_xref=GO_REF:0000001; with=SGD:S000000961; date=20190108"
/GO="aspect=F; term=DNA-binding transcription factor activity, RNA polymerase II-specific; GOid=GO:0000981; evidence=ISS; db_xref=GO_REF:0000001; with=UniProtKB:Q14919; date=20190108"


which agrees with human and mouse orthologs.
I removed GO processes inferences  from PMID:15388803
and will block and report the EC number

The rest of the annotation from PMID:15388803 is probably Ok

**Comment by mah11** [comment]
I think everything on the list is 

a) fixed; or
b) not in the network for reasons we understand (with notes for posterity above); or
c) mcb1

reopen if you disagree
