### ISSUE TITLE
cell division site -° cleavage furrow?

### ISSUE THREAD

**Issue by Antonialock** [pombase/curation#2414]
I have often annotated to "cell division site" when a protein localizes to the midpoint of a cell (when it looks like a septum) but this doesn't really fit the def.

is "cleavage furrow" the correct term to use when you see a load of protein like this? (cells havent divided yet but they are obviously pretty on the way and organised in terms of getting the septums together)

![Screenshot 2019-05-31 at 01 17 46](https://user-images.githubusercontent.com/12727506/58673126-fe0eb380-8341-11e9-8054-cf7a04859d92.png)

**Comment by Antonialock** [comment]
actually maybe cleavage furrow could be later.....and it is a child

....I just thought that the "eventually" part of the def of "cell division site" implied that it's a much narrower term.

**Comment by ValWood** [comment]
I agree cleavage furrow is tricky. It's slightly orthogonal with other components. 

I have used this


cleavage furrow leading edge
-- | --
The 'trough' of the cleavage furrow. This is the part of the cleavage furrow closest to the contractile ring.

to pinpoint things that are clearly at the leading edge of the furrow
as in this pic https://www.pombase.org/reference/PMID:30044717

To use "furrow" I would say the gene product has to be clearly in the invagination.

for Tpk2? we probably need "plasma membrane of cell division site" as a cell division site part ( since we have "plasma membrane of cell tip")

**Comment by ValWood** [comment]
so in summary

To use "furrow" I would say the gene product has to be clearly in the invagination.
