### ISSUE TITLE
review ubiquitin binding annotations

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#272]
[wrong summary removed 2015-10-22 mah]

**Comment by mah11** [comment]
All reviewed. Most were already correct; I did a couple of little fixes (side note: Rhp23 both binds ubiquitin and is ubiquitinated).

One thing for Val, because she has a session going for PMID:16096059: according to the paper, Cut8 is polyubiquitinated, so I've deleted the annotation to GO:0031593 ! polyubiquitin binding. I didn't see anything about Cut8 binding ubiquitin.

**Comment by ValWood** [comment]
sounds right....
