### ISSUE TITLE
rum1 phosphorylation sites, unannotated

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2838]
from PMID:32361273
These two motifs (39IDEIPE44 and 80LERCMEE86) surround the two main phospho-sites targeted by CDK (T58 and T62) (Benito et al., 1998) (Figure 6A).

- [x] Benito et al., 1998 = PMID:9430640

**Comment by ValWood** [comment]
PMID:9430640

**Comment by ValWood** [comment]
Assigned to me and JAcky, whoever gets to it first

**Comment by ValWood** [comment]
To avoid the progressive shortening of the cell, this mutant expands the G1 phase, a pro- cess that requires Rum1 and Ste9 activities. In their absence, wee1-50 cells become shorter in every cycle, eventually losing their viability (Moreno and Nurse, 1994; Correa-Bordes and Nurse, 1995) 

Might be in Moreno PMID:8121488
Since 
Correa-Borges and Nurse, is curated

**Comment by JackyVH** [comment]
Val this paper has something about rum1 phosphorylation site

iScience

  *
  *   <https://www.ncbi.nlm.nih.gov/nlmcatalog?term=%22iScience%22[Title+Abbreviation]>
  *   <https://pubmed.ncbi.nlm.nih.gov/32361273/#>

. 2020 May 22;23(5):101063.
doi: 10.1016/j.isci.2020.101063.Epub 2020 Apr 16. It’s from Sandra Lopez-Aviles lab

Sent from my iPhone

On 13 Oct 2020, at 17:15, Val Wood <notifications@github.com> wrote:

﻿

To avoid the progressive shortening of the cell, this mutant expands the G1 phase, a pro- cess that requires Rum1 and Ste9 activities. In their absence, wee1-50 cells become shorter in every cycle, eventually losing their viability (Moreno and Nurse, 1994; Correa-Bordes and Nurse, 1995)

Might be in Moreno PMID:8121488
Since
Correa-Borges and Nurse, is curated

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpombase%2Fcuration%2Fissues%2F2838%23issuecomment-707852124&data=02%7C01%7C%7Cd97722a909f94c2563ff08d86f932bf3%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637382025168806630&sdata=LfqkdMrHV9paDfSXq11NUP6CJMr4uVEcTpHq1Vu7j8k%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADKVK2DBHLK5EHNMRXFF24DSKR4JHANCNFSM4SE3DW7Q&data=02%7C01%7C%7Cd97722a909f94c2563ff08d86f932bf3%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637382025168806630&sdata=qcyltcuIV0Z0Xwgtbzin4o7OCL8AOQOHG3MU230ET1A%3D&reserved=0>.

The Francis Crick Institute Limited is a registered charity in England and Wales no. 1140062 and a company registered in England and Wales no. 06885462, with its registered office at 1 Midland Road London NW1 1AT

**Comment by ValWood** [comment]
Yes, Ruth Martin curated this week:
https://www.pombase.org/reference/PMID:32361273
it's really nice to see these phosphatase papers! This is the paper that  the text in the first item in the ticket is from  made me realise we had the holes and should prioritise some of these older ones.

**Comment by ValWood** [comment]
actually I have PMID:9303310 in approval
