### ISSUE TITLE
two-component phosphorelay

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2882]
https://www.pombase.org/term/GO:0000160

@Antonialock another question, sorry!

Aren't the map kinases downstream of the phosp[horelay system?

<img width="1204" alt="Screenshot 2020-11-02 at 17 38 00" src="https://user-images.githubusercontent.com/7359272/97900241-4fd71c80-1d32-11eb-8488-63fb4cd2fb6b.png">

**Comment by Antonialock** [comment]
mak1/2/3 are the histidine kinases

**Comment by ValWood** [comment]
oh yes! I always get those mixed up

**Comment by Antonialock** [comment]
I can't say for sure (because I don't think it is fully known, and I don't remember exactly how much is known to date), but there is a convergence somewhere in this pathway. 

I think mak1/2/3 are believed to somehow sense turgor pressure and therefore are sensors (or relay sensing of) osmostress.
Components downstream of the histidine kinases are also fed oxidative stress signals, but those signals come from other sensors/relay proteins (other than the histidine kinases - as far as I remember).

**Comment by ValWood** [comment]
no I think it is fine. I was confused...
