### ISSUE TITLE
PMID:33511417 see if  GIs can align with multi-allele phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2968]
multi-allele phenotypes and GIs did not align very well
https://www.pombase.org/reference/PMID:33511417

1. review

2. If these are still radically different (maybe it was not desirable to make the GIs for multi-allele phenotypes or vice versa) this would cause problems for:

https://github.com/pombase/canto/issues/2301

**Comment by mah11** [comment]
I'll stick an oar in since I did approval for this paper.

The 'synthetic' interaction phenotypes are mostly growth at high temp or on TBZ, and are mostly captured (exceptions below). Data in figs 5 and 6D. Some double mutants have phenotype but not interaction annotations because the double mutant is the same as one of the single mutants.

The 'rescue' interaction phenotypes are either centromere otr transcript levels (fig 6C), which are captured, or levels of protein-coding and antisense transcripts that would be kind of a nightmare to curate informatively (look at fig 4, and boggle).

Feasible adjustments:
- could add 'synthetic growth defect with' to pst2 dbl2, and maybe also to clr4 dbl2 (std t) but it's subtle
- perhaps also change dcr1 dbl2 to 'synthetic growth defect with' because there's a tiny bit of growth at high temp

**Comment by ValWood** [comment]
I was trying to  figure if there are any cases where we would not want to make a multi-gene annotation but we would want a GI.  I thought here might be but now I think it would be OK. In this situation:


<img width="1216" alt="Screenshot 2021-03-04 at 09 16 42" src="https://user-images.githubusercontent.com/7359272/109941033-9893e780-7cca-11eb-989a-6e30a54ef2a0.png">

they line up quite nicely. You can see every  GI in the multi gene (yesterday I thought some were missing but they aren't) connecting to the phenotypes here would be really helpful.

i.e.
hip1  is rescued by dbl2 (normal centromere repeat level)
hip3  growth defect is increased further by dbl2   (this could be added if bioGRID is correct?)
hip4 is rescued by dbl2 (normal growth on TBZ)
slm9 is rescued by dbl2 (normal centromere repeat level)

difference.
Biogrid has synthetic lethal for dbl2/dcr1, we have decreased growth with high severity.

so it is a good consistency check.

I can envisage that we might not want to create an inviable multigene phenotype if we got a HTP GI screen but we can discuss that.... we would not want to do it in the multigene workflow anyways......

**Comment by ValWood** [comment]
corrected hip3/dbl2 is there also.
so all the GIs are curated as multigene but there are 2 v. subtle differences.

**Comment by mah11** [comment]
I made the adjustments noted [here](https://github.com/pombase/curation/issues/2968#issuecomment-789062764).

**Comment by ValWood** [comment]
We can close this. Will continue to assess if there are GI's that we would not want to curate in multi-gene but I think largely we will be OK...if not we can make adjustments.
