### ISSUE TITLE
new PRO terms/IDs

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3073]
https://github.com/PROconsortium/PRoteinOntology/issues/253#issuecomment-881472091
PR:000050542 = Spom-gtr1/GDP+
PR:000050543 = Spom-gtr1/GTP+
PR:000050545 = Spom-gtr2/GDP+
PR:000050546 = Spom-gtr2/GTP+

https://github.com/PROconsortium/PRoteinOntology/issues/246#event-5031858666
PR:000050538 gad8/Phos(S527)

https://github.com/PROconsortium/PRoteinOntology/issues/245
PR:000050529 hhf1/Me1:(K20)
PR:000050530 hhf1/Me2:(K20)
PR:000050531 hhf1/Me3:(K20)
PR:000050532 hhf2/Me1:(K20)
PR:000050533 hhf2/Me2:(K20)
PR:000050534 hhf2/Me3:(K20)
PR:000050535 hhf3/Me1:(K20)
PR:000050536 hhf3/Me2:(K20)
PR:000050537 hhf3/Me3:(K20)

https://github.com/PROconsortium/PRoteinOntology/issues/254#issuecomment-882612446
Phosphorylated: PR:000050548 pxl1/Phos:(S3/S24/S31/T55/T64/S67/S97/S136/T214)
Unphosphorylated: PR:000050549 pxl1/UnPhos:(S3/S24/S31/T55/T64/S67/S97/S136/T214)

**Comment by mah11** [comment]
Did you look in the mini-ontology?

**Comment by ValWood** [comment]
No , I don't remember requesting them, they. were still queued in my inbox...

**Comment by mah11** [comment]
- The mini-PRO file used for the website lives here (our SVN), in case you want to see if we've got a particular term: `pombe-embl/mini-ontologies/pombe_mini_PR.obo`.
- Even if an entry isn't in mini-PRO yet, you don't absolutely need to open a ticket here: 
  - I've reactivated an old reminder to myself to check the PRO tracker weekly for mini-PRO update fodder; and
  - any PRO ID that's used in an annotation but not found in mini-PRO gets reported in logs (so if I miss anything in the previous step, it gets caught).
- You requested the histone terms and gad8 (PR:000050529-50538) in #3021. I added them on June 11.
- The display strings suggested for gtr1, gtr2, and pxl1 don't use our syntax. Entries with correct display names have been in the file since last week Friday (July 23).
