### ISSUE TITLE
crm1 mixture of has_input and has_direct_input

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3083]
on "nuclear export signal receptor activity"
figure out why

**Comment by mah11** [comment]
There were two things going on here. One is that there wasn't a website configuration entry for this branch of MF; I've just committed an addition.

The other is that most of these date to before the Canto extension interface, so the relation would've been added manually, and that was done with a mix of has_input and has_direct_input (the Canto config now slots in has_substrate upon annotation, but the whole system somehow knows that has_substrate = has_direct_input, so it all turns out fine). I've changed the ones that had has_input, so it should all look better tomorrow.

**Comment by ValWood** [comment]
Thanks - that will improve other carriers too!
