### ISSUE TITLE
Tricky column_17 value for SPAC25A8.01c curate PMID:18422602

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3112]
SPAC25A8.01c/fft3 has this two values in the column_17 qualifier, and a with qualifier:

```
FT                   /GO="aspect=F; term=protein binding; GOid=GO:0005515;
FT                   evidence=IPI; db_xref=PMID:18422602;
FT                   with=PomBase:SPBC557.03c;
FT                   column_17=PomBase:SPBC557.03c,PR:000045536; date=20080718"
```

Is this correct?  If so, I'll need to change the loader.

**Comment by ValWood** [comment]
This is wrong. The 'active form' should be attac hed to. pim1.
So you can ignore. I'll flag this paper for Canto, high priority.

**Comment by mah11** [comment]
I've had a go at this paper, and fixed the column_17 problem that spawned this ticket. But it might be good to have a second set of eyes on the rest.

https://curation.pombase.org/pombe/curs/bc16edfb200d65c2/ro/

Fft3 binds Spi1, and somehow increases the GEF activity of Pim1 towards Spi1.

I've annotated fft3 to GO:1905099 ! positive regulation of guanyl-nucleotide exchange factor activity ... it feels weird, because maybe there shouldn't even be a BP, but on the other hand I'm not sure an "activator" MF term exactly fits either. The MF regulator MFs are all defined as binding to the regulated thing, and this paper doesn't have evidence of fft3 binding to pim1 ("data not shown" says no fft3-pim1 binding under their conditions).

Also, I didn't try to annotate anything from Figure 4 - histone H3 seems to negatively regulate Rna1 Ran GAP activity, but there isn't binding data for an "inhibitor" MF ... and fft3 seems to do negative regulation of negative regulation ... maybe something could be done in a GO-CAM? Or should we request BP GAP regulation terms? Seems like a mess waiting to happen.

**Comment by ValWood** [comment]
I will take a look. I'm never sure how to annotate regulators of GAP activity.

All regulations of MF in the process ontology are slated for obsoletion, so I will probably remove
GO:1905099 ! positive regulation of guanyl-nucleotide exchange factor activity

This is one that I might be able to get input on on the chromatin call today.

**Comment by ValWood** [comment]
Looks OK.
