### ISSUE TITLE
Duplicated "from" value

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3115]
The "from" has the same GO ID twice ("GO:0004652,GO:0004652") which ends up in the GAF output file.  It seems harmless otherwise.  I'll investigate the source later.

```
PomBase SPAC821.04c     cid13           GO:0003730      GO_REF:0000036  IC      GO:0004652,GO:0004652   F       poly(A) polymerase Cid13                protein taxon:4896  20110716 PomBase
```

**Comment by ValWood** [comment]
One of those should be 
GO:0003729    mRNA binding
(which isn't visible because it is an IEA and suppressed by the IC to GO:0003730)


We could actually make an EXP annotation for this term from
https://www.pombase.org/reference/PMID:12062100
which is partially curated because we already have


polynucleotide adenylyltransferase activity
  | cid13 has substrate suc22
which demonstrates an mRNA substrate

We can prioritise this paper for backlog curation

**Comment by mah11** [comment]
all fixed
