### ISSUE TITLE
Transcript IDs in GO_ORFeome_localizations2.txt

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3145]
The annotations for SPAC1556.06.1 and SPAC1556.06.2 are causes some loading problems.  It looks like there is only one transcript in for SPAC1556.06 now so could these two lines be merged and the ".1"/".2" removed?

`pombe-embl/external_data/external-go-data/GO_ORFeome_localizations2.txt`

```
PomBase     SPAC1556.06.1   SPAC1556.06.1           GO:0005829      PMID:16823372   HDA             C                       gene    taxon:4896      20091111        PomBase
PomBase     SPAC1556.06.2   SPAC1556.06.2           GO:0005829      PMID:16823372   HDA             C                       gene    taxon:4896      20091111        PomBase
```

**Comment by ValWood** [comment]
This one *should * have 2 transcripts. IIRC think there is a meiotic version and a mitotic version. I can look into that this week.

But these annotation should apply at the gene level because I'm pretty sure  we have any information about different locations for different versions, and certainly that information would not have been available from the orfeome data so I will fix this now.

**Comment by ValWood** [comment]
fixed in GO_ORFeome_localizations2.txt
