### ISSUE TITLE
FYPO:0004087 is probably FYPO:0003787

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3235]
increased number of cells with astral spindle microtubules (FYPO:0004087) is most likely long mitotic spindle microtubules protruding beyond spindle pole body (FYPO:0003787)

While curating PMID:26031557

See also https://github.com/manulera/discussions_curation/issues/6

* In pkl1 gene page, there is an annotation for FYPO:0004087 in pkl1D.

* The annotation comes from an old paper with microscopy from early 2000. This was not reported in PMID:26031557 and PMID:25987607 where the process of protrusion formation in pkl1D was studied in detail. My guess is that in the 2000 papers they counted these protrusions as astral microtubules.

* Also **the annotation is listed as population phenotype**, and not cell phenotype.

![Screenshot 2022-04-27 at 10 59 55](https://user-images.githubusercontent.com/22526102/165504901-1c29d2bf-314a-490f-ac6e-7976654942d2.png)

**Comment by ValWood** [comment]
I think this was a population phenotype because they counted the cell numbers presented in the table, but we did not actually see the phenotypes. I am very happy to delete the annotation (I have done this already)  since it is data not shown. It probably should not have been curated.
I will also obsolete the FYPO term, once I work out how to do this. I haven't done a term merge or obsoletion yet....
