### ISSUE TITLE
orthlogs, sphingo/ lipid metabolism

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3244]
@dexink

- [x]  SPBC660.17 - Schizosaccharomyces specific protein, uncharacterized 
-> YGR016W (ER protein),  from jackhmmr. Need t double check if more broadly conserved

- [x] (lcb3 removed)/ SPAC23A1.05 
is currently annotated as "serine palmitoyltransferase subunit A Lcb3 (where from ?) FIXED  is  S. cerevisiae tsc3 orthlog  YBR058C-A (NOT lcb3 )

- [x] add GO ISO to sphingolipid metabolism and SPOTs complex

**Comment by ValWood** [comment]
There are not so many missing orthologs
https://github.com/pombase/curation/issues/3245
The main question is whether all of the annotations are correct.

**Comment by ValWood** [comment]
Also to look for:
 - [ ] S. cerevisiae YPC1/YDC1 ortholog
 - [ ] S. cerevisiae CSG2 ortholog
 - [ ] S. cerevisiae LDB16 ortholog

**Comment by dexink** [comment]
**RE: YPC1/YDC1, definition**
[UniProt lists two](https://www.uniprot.org/uniprot/?query=ypc1&fil=organism%3A"Saccharomyces+cerevisiae+(strain+ATCC+204508+%2F+S288c)+(Baker's+yeast)+[559292]"&sort=score) in their database with a precursory search, one per each name (YPC1 and YDC1)
- both are annotated as being largely transmembraneous
- KEGG orthologs are negative for S. pombe
- KEGG does list the two as paralogs of one-another (ENSEMBL corroborates this)
- Both entries in ENSEMBL specifically list them as not having orthologs across all relevant species of Schizosaccharomyces ([YDC1, bottom](https://fungi.ensembl.org/Saccharomyces_cerevisiae/Gene/Compara_Ortholog?db=core;g=YPL087W;r=XVI:383455-384408;t=YPL087W_mRNA#list_no_ortho); [YPC1, bottom](https://fungi.ensembl.org/Saccharomyces_cerevisiae/Gene/Compara_Ortholog?db=core;g=YBR183W;r=II:596115-597065;t=YBR183W_mRNA#list_no_ortho))

**Comment by dexink** [comment]
**RE: CSG2, definition**
Purportedly part of a heterodimer via [UniProt with either CSH1 or SUR1](https://www.uniprot.org/uniprot/P35206)
Interesting, this is not corroborated by the listed binary interactions on the same entry page

KEGG orthologs is negative for S. pombe
UniProt page reads the following for the function in S. cerevisiae, which links ceramide biosynthesis to inositol derivatives: "Required for calcium regulation. May regulate calcium accumulation by a non-vacuole organelle. Also regulates the activity of CSH1 and SUR1 during mannosyl phosphorylinositol ceramide synthesis."

Inositol metabolic pathways may need better resolving; potential for replacement of other central metabolism that is missing in S. pombe (?)

**Comment by dexink** [comment]
Possibly interesting:
STRING network for [SPCC1450.15.1 (pig-F/3-ketosphinganine reductase fusion protein)](https://www.pombase.org/gene/SPCC1450.15) links ceramide biosynthesis to tryptophan biosynthesis, mTor, the erf2-erf4 complex, and a chaperonin-containing t-complex:
[Network (no textmining, no co-expression; 2nd shell = no more than 30 interactors)](https://version-11-5.string-db.org/cgi/network?networkId=bTyegGV96fZ8)

Nodes that may be of particular interest are [SPCC320.14 (a racemase)](https://www.pombase.org/gene/SPCC320.14) and [SPBC119.09c](https://www.pombase.org/gene/SPBC119.09c), a purported member of the SPOTS complex for which Pombase has its characterization status listed as "biological role inferred". Even more interesting, the latter node, as shown in the network, is linked directly to [SPAC23A1.05](https://www.pombase.org/gene/SPAC23A1.05), the protein that we determined had somehow been misannotated at some point as "lcb3"(!). (Recall that we were able to determine that the true _S. cerevisiae_ Lcb3 ortholog in _S. pombe_ was actually [SPAC823.11](https://www.pombase.org/gene/SPAC823.11) (currently annotated as "sgp1" in Pombase); it is also in the network and is clustered, as would be expected, with the other nodes linked to ceramide biosynthesis)

Do we think that SPAC23A1.05 was misannotated as Lcb3 was so-assigned because of an observed link to the other proteins we've confirmed as being involved in ceramide biosynthesis, and so in the past had been mistaken for one of the remaining players missing from the _S. pombe_ pathway compared to that in _S. cerevisiae_?

Ultimately, it's possible that we may want to add a D-tryptophan (or D-amino acid) pathway to the list of possible alternative routes of tryptophan degradation in _S. pombe_. Thoughts?

**Comment by dexink** [comment]
To add to the interest in the misannotated "lcb3" protein, Sgp1 ([SPAC823.11](https://www.pombase.org/gene/SPAC823.11)), it appears to be a regulatory target of Ser1, a regulator of sterol biosynthesis
![image](https://user-images.githubusercontent.com/7029234/168423283-2bdaa10b-6c9a-479d-83c1-4c8c38752554.png)

Other interesting targets of Ser1 (under hypoxic conditions) include:
- [SPAC186.08c (our mysterious **L-lactate dehydrogenase**)](https://www.pombase.org/gene/SPAC186.08c)
- [SPAC9.02c (**polyamine** N-acetyltransferase)](https://www.pombase.org/gene/SPAC9.02c)
- several **_S. pombe_-/fungal-specific** proteins
- some unknowns (including a "**conserved unknown**" aldo/keto reductase, [SPBC215.11c](https://www.pombase.org/gene/SPBC215.11c))
- "implied in cellular detox" proteins [SPBC21C3.15c](https://www.pombase.org/gene/SPBC21C3.15c) and [SPBC23G7.10c](https://www.pombase.org/gene/SPBC23G7.10c)
- an inner membrane transporter, [SPCC613.02](https://www.pombase.org/gene/SPCC613.02), for which only an _S. japonicus_ ortholog is listed in Pombase

**Comment by dexink** [comment]
RE: D-Tryptophan and Tryptophan degradation
Another reaction is listed [for this molecule in MetaCyc](https://biocyc.org/compound?orgid=META&id=D-TRYPTOPHAN#tab=RXNS) that I did not notice before; there are promiscuous amino acid-utilizing reactions that feed into ceramide/Sphingolipid metabolism pathways:
![image](https://user-images.githubusercontent.com/7029234/168440287-5ab9ca20-ebb8-40d7-aa40-4e44f89d0653.png)

**Comment by ValWood** [comment]
SPBC119.09c, SPAC23A1.05 and SPAC823.11 should be updated tomorrow.
I will check. I had already done it but not committed.

**Comment by ValWood** [comment]
>Do we think that SPAC23A1.05 was misannotated as Lcb3 because of an observed link to the other proteins we've confirmed as being involved in ceramide biosynthesis, and so in the past had been mistaken for one of the remaining players missing from the S. pombe pathway compared to that in S. cerevisiae?

It might be related to this link in some way, but I think it was an actual mistake because SPAC23A1.05 and the real LCB3 are nothing like each other in length (I would always want to see some support b before adding an ortholog predicting).

**Comment by ValWood** [comment]
>Ultimately, it's possible that we may want to add a D-tryptophan (or D-amino acid) pathway to the list of possible alternative routes of tryptophan degradation in S. pombe. 

yes if this looks like the route. We can  begin to model this in Noctua training session.

**Comment by ValWood** [comment]
CLosing this one as all should be addressed went he pathways are built
