### ISSUE TITLE
cdc7 synonyms

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3263]
Hi @ValWood 

Is it normal that cdc7 is the main name for a gene and a synonym for others?
![Screenshot 2022-05-25 at 10 48 25](https://user-images.githubusercontent.com/22526102/170234486-339f2c44-3f36-45ab-8314-09c3f0c3acae.png)

**Comment by ValWood** [comment]
Yep. A gene primary name must be unique, but  synonyms may be shared, or be primary names of other genes. Often there are clashes and we resolve the primary name but keep other names used in the literature as synonyms.

We include Cdc7 for Hsk1 because it is the human, and S. cerevisiae name,  and when referred to in the literature the complex is often called Cdc7-Dbf4 complex (A GO synonym for the complex).

We have this problem quite a lot. Especially for things first isolated as mutants before they were physically mapped (like cdc). Where we can we would align the names but this is not possible if a name space was already used by another grene/protein.

**Comment by manulera** [comment]
😮
