### ISSUE TITLE
sod2Δ appearing on nhe1 page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3277]
https://www.pombase.org/gene/SPAC977.10

sod2Δ appears attached to nhe1 in this session:
https://curation.pombase.org/pombe/curs/2225bf5e95a71d70/ro/

There are a bunch of sod2 alleles attached to nhe1 in this session:
https://curation.pombase.org/pombe/curs/eb4340d44f575950/ro/

Sorry I don't know how this is happening.

Probably related to pombase/curation#3276

**Comment by ValWood** [comment]
similar reason. neh1 used to be called sod2. Will fix shortly.

I thought these appeared in one of the logs though?
Either
https://curation.pombase.org/dumps/latest_build/logs/log.2022-06-13-21-25-27.chado_checks.badly_named_deletion_alleles

or this one
https://curation.pombase.org/dumps/latest_build/logs/log.2022-06-13-21-25-27.chado_checks.alleles_instance_of_gene

or
https://curation.pombase.org/dumps/latest_build/logs/log.2022-06-13-21-25-27.chado_checks.duplicate_allele_descriptions

I know I have seen some similar, because I Ihave removed from PHAF files?

**Comment by ValWood** [comment]
This name change was approved years ago by PY, so I'm surprised we didn't update them all at the time.
Now all of the sodium transporter ones are nhe1delta with sod2delta as synonyms
I think I got them all but sometimes there are  possibly 2 papers from the same 1st author. Will check tomorrow.

**Comment by ValWood** [comment]
I think all sod2delta has gone from nhe1
