### ISSUE TITLE
occurs_at and occurs_in for physical location of protein binding GO molecular function

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3283]
While curating PMID:15689489 I went into the ase1 page to add some GO terms that were missing. I checked whether it was shown to interact with cls1. The interaction is there, and it specifies in the midzone, which is correct, but it also occurs in interphase microtubule bundles, so I wanted to add that location to the interaction.

I went into the curation session to add this, and I noticed that when I add the `physical location` of a `protein binding` molecular function, it generates an `occurs_in` annotation extension, while the existing annotation has an `occurs_at` annotation extension.

![Screenshot 2022-06-21 at 12 52 25](https://user-images.githubusercontent.com/22526102/174785226-d07e86c3-885d-4421-874e-247cf51542f9.png)

I am not able to find the documentation for `occurs_at` in geneontology wiki, but I can find the `occurs_in`:

https://wiki.geneontology.org/Annotation_Extension_Relation:occurs_in
https://www.ontobee.org/ontology/RO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000066

I found this entry in the wiki in which it seems that occurs_at would have been renamed as occurs_adjacent_to? But this term is also not in the ontobee nor in the go list of annotation extensions.

https://wiki.geneontology.org/Ontology_meeting_2019-11-18#Occurs_at_-%3E_occurs_adjacent_to?

**Comment by pgaudet** [comment]
Hi @manulera 

The page you link to is meeting minutes (https://wiki.geneontology.org/Ontology_meeting_2019-11-18#Occurs_at_-%3E_occurs_adjacent_to?); this was a discussion and was not implemented. 


We have decided a while ago to only use 'occurs_in'. For this documentation we have more complete documentation
https://wiki.geneontology.org/Annotation_Extension_Relation:occurs_in
(although documentation can always be improved). 

We have deprecated usage of occurs_at, because while in English this sounded more grammatically correct, in particular for genomic regions, in fact we were not able to define these occurs_in and occurs_at differently. 

I think PomBase has kept on using occurs_at for genomic regions for readability, but these divergences can cause confusion. 

I hope that helps.

**Comment by pgaudet** [comment]
See also https://wiki.geneontology.org/Annotation_Extension_Relation:occurs_at

**Comment by ValWood** [comment]
Right, I think i. missed the deccision not to implement  'occurs_adjacent_to' (or I totally forgot).

So, we use occurs_in for everything behind the scenes. But  for display we can configure the label for a more user friendly label depending on the ontology position (i.e, we use phosphorylates  for display for transporters in Canto instead of has_input).

Here, I  think the default has applied to your term (occurs__in_, but we have a display label configured for  
'spindle' occurs_at

<img width="639" alt="Screenshot 2022-06-22 at 08 14 51" src="https://user-images.githubusercontent.com/7359272/174967276-bb370aad-6637-4357-a1f0-2e4cdd4188b0.png">

We can look at the config and apply the display labels higher up the tree if it makes more sense lexically. Or we could  just use occurs_in everywhere (although this does look especially weird for some terms).

**Comment by ValWood** [comment]
@manu I think internally we can use occurs_in or occurs at  as the label (whichever looks correct, edit in the text box),  for GO everything is exported as occurs_in 
(we would need to check this)
