### ISSUE TITLE
/note= 

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#33]
Need to follow up on handling of notes

On 09/02/2011 19:12, Kim Rutherford wrote:
&gt; On Wednesday 9 February 2011 at 18:20:36, Val Wood wrote:
&gt;
&gt;&gt; There are ~9575 notes on various features. Many non-CDS features have a
&gt;&gt; single note in free text (because controlled_curation is only allowed in
&gt;&gt; GeneDB for CDS)
&gt; The Sanger loader stores /notes in the featureprop table with a
&gt; property type of "comment" (as far as I can tell).  There are only 2539
&gt; comment properties in the database, so I have a bit of investigation to
&gt; do.
&gt;
&gt; The breakdown of comments by type is:
&gt;
&gt;   count |     name
&gt; -------+---------------
&gt;     174 | tRNA
&gt;      13 | rRNA
&gt;     391 | ncRNA
&gt;     361 | repeat_region
&gt;       6 | snoRNA
&gt;     372 | polypeptide
&gt;    1222 | region
&gt;
&gt; The Sanger loader has cleverly not bothered to put any on the gene
&gt; features.
&gt;
&gt;
&gt;&gt; These are mainly "a bit  controlled" and can be refined quite easily
&gt;&gt; into some sort of vocabulary.
&gt;&gt; You mentioned that 366 notes are on CDS...I would like to get rid of
&gt;&gt; these if possible so if you can send me a list at some point (no hurry
&gt;&gt; as I won't have time for a few weeks)
&gt; Do you need a list of the notes, or a list of the CDSs that have notes?
&gt;
&gt; Kim.

Val
There are a bunch of notes on
5'UTR
3'UTR
LTR
etc

Original comment by: ValWood

**Comment by ValWood** [comment]
Down to  784 .....so it isn't going up....

**Comment by ValWood** [comment]
Most of the notes are on non-CDS features, and some of these might actually be displayed/used, because they also act as the "description" of the feature.

The  CDS ones are definitely ignored.

**Comment by ValWood** [comment]
772.
 I can see a lot which can be deleted, as they don't add anything, many are covered by the SO annotation. Will do this before final chado load. 

The remaining useful ones can migrate to controlled curation (warning or misc)

@Antonialock  are these any use since you updated the tRNA annotations? If not we can delete all of these:
e.g.
/note="tRNA Ser anticodon CGA, Cove score 77.58"

/note="NuMT, 94% identity to mitochondrial chromosome 
type
can go, covered by SO ID

anything which mentions a frameshift should be in 'frameshift' format warnings
 e.g. /note="PMID:16823372 predict a frameshift at base 1684,

 /note="warning, gene name change"
should move to standard format warning (in controlled curation)

can be deleted, is now annotated:
chromosome1.contig:FT                   /note="candidate ortholog S. cerevisiae YJL062W-A"

nice Friday afternoon tasks.
Will  can work through these and then I'll add more.

**Comment by ValWood** [comment]
moving to low priority because of the chado final load requirement.
I could just wipe them but theres some useful legacy information in this list that needs to be recorded.

**Comment by ValWood** [comment]
...708  migrated lots to warning, synonyms,  name descriotion, dbxref
I thought I had done more than that....

**Comment by ValWood** [comment]
...606, done for the day

**Comment by Antonialock** [comment]
yeah that trna one can just go, I don't recognize it.

**Comment by ValWood** [comment]
Yep, I have been deleting these, they are really old (very first pass annotation!). The codon is covered by the GO annotation, and the score is pretty meaningless. The ones I have kept are where the reported codon differs from the annotated codon. At the end I'll open a ticket for these to be checked.

**Comment by ValWood** [comment]
Down to 514. That's enough of that for today....

**Comment by ValWood** [comment]
Down to 459
 
need to do chromosome 2 and then I think that is ALL of the CDS notes. 
After that, most are required  for  feature descriptions but need to be part of some standard vocabularies...should mainly map to SO etc. At this point I'll make a new ticket...

**Comment by ValWood** [comment]
down to 425......
