### ISSUE TITLE
Cohesin GO terms

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3302]
cc @ValWood 

I noticed that some components of the cohesin complex were not annotated to [GO:0007064](https://www.pombase.org/term/GO:0007064) mitotic sister chromatid cohesion (rad21 and psm1). I will annotate them.

However, shouldn't this links be inferred from GO, since they belong to the mitotic cohesin complex, which in turn is linked to mitotic sister chromatid cohesion through `Capable of part of`?

![Screenshot 2022-07-28 at 16 22 31](https://user-images.githubusercontent.com/22526102/181575890-7cdeb8b2-ef9e-473f-a7e8-f6a7f0defe55.png)

![Screenshot 2022-07-28 at 16 23 46](https://user-images.githubusercontent.com/22526102/181576163-85d57981-d6bf-486a-9929-1e3d483f2b1d.png)

I noticed that in the json file of go that I use to build the maps, the "dashed line" annotations are not there. I assume that these connect GO terms of different type. Perhaps we are not using those links either in Pombase?

**Comment by manulera** [comment]
I can see now that these relationships are only in the go-plus file, not in the go file (in either owl / obo / json format)

http://geneontology.org/docs/download-ontology/

**Comment by ValWood** [comment]
The annotations are there, but they are hidden because the rad21 and psm1 subunits are also annotated to
a child 

GO:0062022 | mitotic cohesin ssDNA (lagging strand) loading
which is part_of cohesion

but this annotation might be a bit strange, to annotate the subunits of the loaded complex  itself to the. "loading" process.
https://www.pombase.org/term/GO:0007064
https://www.pombase.org/reference/PMID:29358048
 We probably haven't modelled this ideally in GO yet.


also for GO inferences, think currently the GOC only makes inferences over part_of (we import these inferences)
the relations between components and processes are fairly new. I'm not sure if there are any plans to make inferences over these but I will find out (we should have most of the annotations instantiated already, because we usually make sure that  processes and complexes align, but this would be a good check)

**Comment by manulera** [comment]
Ok, got it. I won't annotate the genes then. I hadn't seen that GO:0062022 | mitotic cohesin ssDNA (lagging strand) would be a child of [GO:0007064](https://www.pombase.org/term/GO:0007064). I should have gone to the term page!
