### ISSUE TITLE
multiple nucleotide mutations together/ mae2 mutants & gsa1-MN101

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3308]
cc @ValWood 

I sorted out the mae2 mutants from PMID:10187772

There is one that has a nucleotide insertion AND substitution. I will put it as `other` for now, and we can add the type of allele later.
```
UAS1  ↓-359
CCATG-TCCCCTGGCA-ACACCC > Gene
      **** *
CCATG-GTTACCGGCA-ACACCC > Primer


UAS2                  ↓-175
CGAGGTCGACTGGGCTAATCG-TGACGT-TTGGTGGTTGA > Gene
                      **** *
CGAGGTCGACTGGGCTAATCG-ATCGG*-TTGGTGGT > Primer


URS1    ↓-244
AGGGGGA-TCATTCATTT-AAAG > Gene
         ** ****
AGGGGGA-TGGTCACCTT-AAAG > Primer

URS2    ↓-202
AACGTAA-AAATTGCGAG*-GTCGACTGGGC > Gene
        **   ** ***
GAACGTA-CGATTAGGGTC-GTCGACTGGGCT > Primer (reverse complemented)

URS3        ↓-186
GCGAGGTCGAC-TGGGCTAAT-CGTG > Gene
             ** ****
GCGAGGTCGAC-TACGTACGT-CGTG > Primer

TATA
       ↓-88
AAATAG-TTATTTAAAA-GTAGGGCTATA > Gene
       * ****
AAATAG-GTCACCAAAA-GTAGGGCT > Primer
```

**Comment by ValWood** [comment]
Yes, I see we don't have a classification for that.
Since we will probably be increasing the classifications (to include chimera, or ectopic localization etc)
 do we need to add 
insertion+ substitution? or  should combine for types that are not used so frequently.

Maybe it is OK just to keep as type 'other' for something used so infrequently?

These are the existing  types for nucleotide:
insertion 132-AATTT.  (1)
substitution A25G, OR A-25G  (324)
deletion 100-200 OR -20--30  (92)

so insertion is already rare (1 use case) - we could combine insertion and substitution maybe?

**Comment by ValWood** [comment]
@kimrutherford

**Comment by manulera** [comment]
> we could combine insertion and substitution maybe?

There is also an instance of substitution and deletion (UAS2) I hadn't noticed when I wrote them, so any combination should be possible. Since the syntax for all changes is different, we could have a 'nucleotide changes' that accepts any comma-separated values.

The only special case would be deletion of a single nucleotide, like in UAS2, which I specified with a single number? (-170 below)

Single deletion: `UAS2(T-175A,G-174T,A-173C,C-172G,-170`
Single insertion: `A-202C,A-201G,G-197A,C-196G,A-194G,G-193T,-192C`

**Comment by ValWood** [comment]
This one is also an undescribable combination:

gsa1-MN101,SPAC3F10.04:allele-2,nucleotide 7 deleted,nucleotide G879 mutated to A,{c0ae8d0a9450e350,5814ffb8ad4a910f,1cc5c597f8a24352,342b99a76cb8f1c4}

It is described very verbosely but I won't improve yet as it will need to be changed in all 4 sessions.

**Comment by manulera** [comment]
These are supported now
