### ISSUE TITLE
Alternative transcripts splicing zas1 (isoforms)

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3309]
@ValWood for the zas1 paper PMID:29735745

There are two alternatively-spliced isoforms, so the aminoacid changes should be referenced to the right isoform. I guess this is extremely rare in Pombe, but how do we handle this?

zas1A: https://www.ncbi.nlm.nih.gov/nuccore/AF199437.1
zas1B: https://www.ncbi.nlm.nih.gov/nuccore/AF199436.1

**Comment by ValWood** [comment]
Collecting thought here:

Not a short answer, but something we need to pick up on. We have a (very old) ticket here where we noted genes which had potential alternative splicing before we had a mechanism to do it.
https://github.com/pombase/curation/issues/61

So far I believe only a few genes have been represented as alternative splice forms in PomBase.
The main ones are the wtf meiotic drivers Midori did these.   This was really necessary because the different isoforms have different GO activities. However, I can't see any alternatively annotated forms of wtfs, so I am not sure we finished the display tickets? We can chat to @kimrutherford  about this.

I did see one that is annotated - tco1, but we have a problem with the display because tco1 alternative transcript does not form a protein https://github.com/pombase/pombase-chado/issues/865 (should probably be represented and an ncRNA not an alternative CDS)

In zas1 case 

"We report here that a gene encoding a protein with three zinc fingers is expressed predominantly to produce a protein containing only two zinc fingers in the fission yeast Schizosaccharomyces pombe. A third zinc finger resides within the in-frame intron that is normally spliced out" 

At the moment the non-canonical form of zas1 is represented,   should we swap this over to the canonical form?



HOW
Syntax is to create features with .1, .2   to the CDS (and UTRs if features with alternative forms are present).

TO DO
Notes
- [ ] Need  rules for when we curate alternative forms (we don't want things for example with a slightly longer or shorter UTR because transcripts are so heterogeneous, so probably only when there is functional data to  attach to the different forms (I.e different expression at a different time, different activity or phenotype etc).

- [ ] We need to decide if alleles should always be described in reference to the canonical form (this might be sensible since most alleles will apply to both isoforms with different coordinates (to discuss).

- [ ] Which tasks are outstanding for Canto? (can we add isoforms to GO and phenotype annotations?)
(we still capture GO annotation for alternative isoforms in artemis. I am not sure if we have ever needed to curate phenotypes on alternative transcripts?
found:
https://github.com/pombase/canto/issues/2351

- [ ] Which tasks are outstanding for Chado?

- [ ] Which tasks are outstanding for  website display?
i.e how did we decide to display alternative GO annotations? alternative translations etc.
This is the only website related ticket I can find:
https://github.com/pombase/website/issues/1788  (and this is more general)

- [ ] Need a list of all known alternatively spliced genes, (should be in https://github.com/pombase/curation/issues/61 and a list of all curated so we can assess if there are any issues.
 
- [ ] How to describe alleles for  a gene with alternative transcripts (should we describe all relative to the canonical isoform)

- [ ]  Documentation , how to curate isoforms (and their alleles and associated annotations).

**Comment by ValWood** [comment]
@kimrutherford we will not get to this immediately, but can you provide a list of all of the currently annotated alternative transcripts so that we have examples?
I could only find tco1 (which likely needs removing)

**Comment by ValWood** [comment]
Are the alleles in the coding sequence or the intron?

**Comment by manulera** [comment]
In the coding sequence of the isoform we don't show right now

**Comment by ValWood** [comment]
Right now we show the unspliced  (minor) isoform (I'm not sure why)
The in-frame intron is flagged as a feature.

but if we have a rule that we always try to represent the major isoform as the canonical form we would need to swap this to the spliced version.

<img width="927" alt="Screenshot 2022-08-02 at 07 06 24" src="https://user-images.githubusercontent.com/7359272/182385138-7b7f5fe2-f7f7-41b4-b79c-7241017212f9.png">
The intron was already flagged as a feature

Choices
1. Always try to represent the 'major' form, in which case this mutant would need to be described as a nucleotide variation. However what type of mutant is it? if it is a removal of the entire intron, we have  a few examples of this. It might be nice to have short hand syntax for this type of construct?

2. Represent the longest CDS (if a protein)   so that we get the most complete translation (which is what we have currently) ? and we are more likely to be able to describe alleles as protein mutations.

option 2 might seem odd for zas1, especially if it is entire intron removal?

**Comment by ValWood** [comment]
corect screenshoot uploaded

**Comment by manulera** [comment]
Showing both transcripts would not be possible?

The mutants are partial deletions that are either done:

* On the wild type sequence, but the aminoacid coordinates provided are referring to the indexes in he shorter variant. As is, they would be wrong because it seems that we are indicating the aminoacid changes on the longer variant. In this case I think indicating the nucleotide truncation is probably the easiest.
* On a cDNA of the shorter variant on which they do partial deletions. I think it might be easier to indicate the missing DNA as well.

**Comment by ValWood** [comment]
>Showing both transcripts would not be possible?

we can show both transcripts.

But I think we will  need to describe variation with respect to one isoform (.1).

This is because alleles are attached to genes in the Chado model.

Also, if we had an allele common to both isoforms, for example removing some amino acids further on than the divergent sequence, say  mutated K401G in zfs1- this would need to be described differently for zfs1.1 and zfs1.2 even though it is the same allele.

If we have examples where both alleles have been assessed for phenotypes, I think we could just  add synonyms or comments to the allele maybe  
comment "note that this allele refers to K370G in zas1.s" 
synonym zas1.2-K370G
I think this would be simpler than changing the way alleles are modelled throughout PomBAse since it is such an edge case for us.
thought @kimrutherford 

Tomorrow we can look at the zas1 structure. I think we need to create both transcripts and make the  new (major) isoform the canonical structure, if I understand your comments correctly?

**Comment by kimrutherford** [comment]
> I think this would be simpler than changing the way alleles are modelled throughout PomBAse since it is such an edge case for us.

Yep.  :-)

Transcript specific GO annotation wasn't too hard to handle because we've always attached GO annotation to transcripts in Chado.  Phenotype annotation is attached to genotypes in Chado and genotypes are connected to alleles so making it transcript specific would be a bit hacky.

**Comment by ValWood** [comment]
@kimrutherford do we have any instrructions for creating alternative transcripts.
We created alternative CDS for zas1. 
/systematic_id="SPBC1198.04c.1"
/systematic_id="SPBC1198.04c.2"
AND REMOVED
/systematic_id="SPBC1198.04c.

But I wasn't sure what to do with the UTRs.
At present we left with /systematic_id="SPBC1198.04c
should we remove this and add 
/systematic_id="SPBC1198.04c.1"
/systematic_id="SPBC1198.04c.2"

Also remind me which annotation should be made where. 
1. We can now make GO annotations from papers in Canto, with isoform IDs
2. If we have a GO annotation that is now isoform-specific I add it to the legacy GO file, if it is isoform-specific 
using the colum17? (does this mean that the isoform-specific GO annotation in Artemis can move to this file)
3. For phenotypes, we will describe the phenotype wrt isoform1 (and note the residues in alternative isoforms in the comment if relevant)

Is there anything else to consider?

**Comment by kimrutherford** [comment]
> do we have any instrructions for creating alternative transcripts.

Sorry, I don't think so.

> We created alternative CDS for zas1.
> /systematic_id="SPBC1198.04c.1"
> /systematic_id="SPBC1198.04c.2"

That sounds right.

> At present we left with /systematic_id="SPBC1198.04c
> should we remove this and add
> /systematic_id="SPBC1198.04c.1"
> /systematic_id="SPBC1198.04c.2"

Yep, make separate UTRs with the systematic_id matches the transcripts.

Here's what we have for wtf4:
```
FT   3'UTR           complement(221149..221198)
FT                   /systematic_id="SPCC548.03c.1"
FT                   /db_xref="PMID:21511999"
FT   3'UTR           complement(221149..221198)
FT                   /systematic_id="SPCC548.03c.2"
FT                   /db_xref="PMID:21511999"
```

> We can now make GO annotations from papers in Canto, with isoform IDs

Yep.

> If we have a GO annotation that is now isoform-specific I add it to the legacy GO file, if it is isoform-specific using the colum17? (does this mean that the isoform-specific GO annotation in Artemis can move to this file)

The GAF loader ignores column 17 at the moment: https://github.com/pombase/curation/issues/3310#issuecomment-1203599442

For annotating transcripts, you'll need to use Artemis or Canto.

> For phenotypes, we will describe the phenotype wrt isoform1 (and note the residues in alternative isoforms in the comment if relevant)

I think that's the best plan for now.

**Comment by manulera** [comment]
This is solved by the new guidelines
