### ISSUE TITLE
PMID:35012333 gde1 allele description 

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3381]
can be a test, I won't attempt to fix during checking. 
Also, I don't know when gde1 was altered, it doesn't have a warning and it wasn't in the recent alterations list.

Please note that our nomenclature for the gde1 alleles follows what is shown in fig S1 (previous annotation for gde1 gene, which had Leu - 58 amino acids upstream of the current Met1- as the the starting codon)

**Comment by manulera** [comment]
Hi @ValWood not sure what exactly they did here. Maybe we can discuss on Zoom. Should be a quick one.

**Comment by ValWood** [comment]
I can ask them. I assumed they were using old coordinates for gde1 but I can't see any record of gde1 changing?

**Comment by manulera** [comment]
Hi @ValWood 

I am not sure what they did here. I don't think this coordinates refer to gde1, even though it would seem so from the text. However, in the paper they mention the gene spx1/pqr1. If shifting the coordinates `L1,Y21F,K25A,N139A` by 210 positions to `L211,Y231F,K235A,N349A`, those aminoacids are present in spx1. I think it might be an allele of this gene where the N-term is truncated or they have engineered it so that transcription starts at that position.
`

**Comment by manulera** [comment]
I think this was solved, since I cannot find the allele anymore.
