### ISSUE TITLE
Histone variant allele naming involving residue numbers

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3453]
cc @ValWood

From what we discussed yesterday. It seems that SGD uses the without-methionine coordinate as an alias, even if that's the name that was used in the paper.

https://www.yeastgenome.org/allele/hht1-K57A

https://www.yeastgenome.org/allele/hht2-K57R

**Comment by ValWood** [comment]
Isn't it strange to change the allele name (that researchers use) rather thn the formal underlying description?
The description is still K56A

Maybe this is a question we should ask the GNC There are  members who work on chromatin biology (Olaf, Yoshi). My feeling is that we could manipulate the  descriptions to be consistent with othre genes, but manipulating the allele names would become very confusing (because, for example hht1 has a K37 and a K38)

@colinlog what is the general consensus in the chromatin community about the with/without methionine naming for alleles (as opposed to gene products, or activities)

**Comment by ValWood** [comment]
OK closing
