### ISSUE TITLE
Alleles I don't understand

### ISSUE THREAD

**Issue by manulera** [pombase/curation#3525]
Hi @ValWood. I am fixing some alleles from PMID:35012333 but I cannot understand what they did. In the paper they mention an update to the coordinates of SPAPB1E7.05, which I see was implemented on our side. However, they say that the starting aminoacid is Leucine? 

> Here, we replaced the chromosomal gde1 gene with alleles encoding active-site alanine mutants H810A-R811A, E845A-D847A, and H860A; in each case we also replaced the Leu1 codon with a Met codon to install a canonical translation initiation site in the ORF.

Looking at their alleles description, they just fit our coordinates if they are shifted by one (see below), as if an extra aminoacid would have to be taken into account. Do you know about this?

|Allele name|Their description| What matches our sequence|
|---|---|---|
|gde1-(met1)E845A,D847A|L1M,E845A,D847A|E846A,D848A|
|gde1-(met1)H810A,R811A|L1M,H810A,R811A|H811A,R812A|
|gde1-(met1)H860A|L1M,H860A|H861A|
|gde1-(met1)WT|L1M|?|
|gde1-(met1)Y21F,K25A,N139A|L1M,Y21F,K25A,N139A|Y22F,K26A,N140A|

**Comment by ValWood** [comment]
I can't remember. I think I needed to mail them about this because I could not figure it out but forgot to do it. 
I will do this.

**Comment by ValWood** [comment]
I has a closer look, the authors based their mutation on this sequence:

![mbio 03476-21-sf001 (1)](https://github.com/pombase/curation/assets/7359272/ae9f9cf5-a9a7-47df-89eb-62f14553e9b7)

So they made the  leucine which is now in the intron  into the methionine
<img width="959" alt="Screenshot 2023-07-06 at 10 59 05" src="https://github.com/pombase/curation/assets/7359272/a0e43b3f-8f37-459e-9f19-82b4cd0826c7">

They didn't determine the correct gene structure in the paper. This happened here:

https://github.com/pombase/curation/issues?q=gde1+is%3Aissue+-assignee%3Amanulera+-label%3Afuture+-label%3Aorthologs+-label%3A%22temporary+reference%22+-label%3Ametabolism+-label%3AGO-CAM+-label%3A%22New+Starter%22+is%3Aclosed
(it may have been independently from the TSS data , or maybe the problem here prompted me to look more closely)

So, how to describe?
This is what actually happened  if I understood correctly.

MKFGER ->MLTDS
(what they described would be MTDS, but MLTDS seems to fit number-wise because there was only an off-by one error in the numbers from their sequence to the corrected version?)

This change should be silent so maybe we could record it in an allele comment rather than complicate the genotypes?

**Comment by manulera** [comment]
Ok, so we can either:

- ignore the L1M bit and remove the annotation to gde1-(met1)WT. It only has `normal vegetative cell population growth` as phenotype.

- add `MKFGES1MLTDA` too all, and keep as is.

Second option is more correct, although a bit less genetically meaningful, I think.

**Comment by manulera** [comment]
@ValWood let me know which of the two options makes more sense.

**Comment by ValWood** [comment]
I went with option 2 and added the genotype comment "This genotype has also MKFGES1MLTDA because of problems with the original gene prediction  but this change is unlikely to contribute to the phenotype."
and deleted the annotation to gde1-(met1)WT. 
v

**Comment by manulera** [comment]
Ok then!
