### ISSUE TITLE
PMID:37787768 PHAF file - some missing FYPO IDs

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3583]
The new PHAF file (`pombe-embl/external_data/phaf_files/chado_load/htp_phafs/PMID_37787768_phaf.tsv`) has 28646 lines without FYPO IDs.  Is that expected?

**Comment by ValWood** [comment]
that sounds more like it, I didn't think it was as high as 100,000!

**Comment by kimrutherford** [comment]
> that sounds more like it, I didn't think it was as high as 100,000!

But why are the lines in the file if there is no FYPO ID?

There are 74874 with FYPO IDs.

**Comment by ValWood** [comment]
@manulera ?

**Comment by manulera** [comment]
Sorry both, those rows should have been dropped. The reason why they were empty is because there were certain conditions that were similar (e.g. two concentrations of the same chemical, or the same treatment 1 day vs. 2 days) and could not really be captured in FYPO + FYECO, so Maria picked some to be dropped. I forgot to remove those lines from the file. Now it should work!

(svn revision 9206)

**Comment by kimrutherford** [comment]
Thanks Manu.
