### ISSUE TITLE
mating type silencing inconsistency to check

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#3709]
https://www.pombase.org/reference/PMID:38181050

<img width="1457" alt="Screenshot 2024-05-07 at 12 17 03" src="https://github.com/pombase/curation/assets/7359272/061d5cbf-141c-4648-8084-1b8552bbbc38">

**Comment by ValWood** [comment]
The GI in S1E does not appear to be curated

**Comment by ValWood** [comment]
Set1 has normal silencing so I don't understand the rescue. That's most likely why I skipped and opened this ticket to check...

**Comment by PCarme** [comment]
From what I can tell, the "normal silencing at mat locus" annotation comes from a reporter gene growth assay from this paper : DOI: [10.1073/pnas.182436399](https://doi.org/10.1073/pnas.182436399). On the other hand, the paper from your first comment shows in Fig. S1E (see picture below) that set1D increase cenH RNA levels in RT-qPCR, and this is partially rescued by the lsd2 mutation.
<img width="168" alt="image" src="https://github.com/pombase/curation/assets/163283897/3d69dc51-30e7-4b6c-9bd4-07748ace4e92">
 I would consider that the evidence supporting an effect of set1D on mat cassette silencing is more convincing since they used a more sensitive approach to detect it. What do you think ?

**Comment by ValWood** [comment]
OK yes, there is clearly an effect.
could delete the old and add anote to the session saying why saying why in case it comes up in future.

**Comment by PCarme** [comment]
FYI, I'm deleting the annotation to "normal silencing" in the Canto session, adding a note to the set1D allele saying "removed "normal chromatin silencing at silent mating-type cassette" annotation on set1D due to conflicting evidence from PMID:38181050", and then going to annotate the effect of set1D and GI in the other session. Is it OK for you ?

**Comment by ValWood** [comment]
Absolutely, yep.

**Comment by PCarme** [comment]
Alright, so we can close this one then.
