### ISSUE TITLE
tRNA embedded in a lncRNA

### ISSUE THREAD

**Issue by kimrutherford** [pombase/curation#3715]
From: https://github.com/pombase/website/issues/2187#issuecomment-2196253287

-----------------------------------------

> Most of them don't look useful but there are some that fold sensibly:
> https://rnacentral.org/rna/URS000230DC2B/4896
> https://www.pombase.org/gene/SPNCRNA.6405

blimey that's a tRNA embedded in a lncRNA, I will take a look at that!

--------------------------------------------

> blimey that's a tRNA embedded in a lncRNA, I will take a look at that!

There are a bunch of other lncRNA genes that look similar:

[SPNCRNA.7042](https://www.pombase.org/gene/SPNCRNA.7042) - https://rnacentral.org/rna/URS000230D4B2/4896
[SPNCRNA.7125](https://www.pombase.org/gene/SPNCRNA.7125) - https://rnacentral.org/rna/URS000230D734/4896
[SPNCRNA.7383](https://www.pombase.org/gene/SPNCRNA.7383) - https://rnacentral.org/rna/URS000230DD31/4896
[SPNCRNA.7463](https://www.pombase.org/gene/SPNCRNA.7463) - https://rnacentral.org/rna/URS000230DE76/4896
[SPNCRNA.2529](https://www.pombase.org/gene/SPNCRNA.2529) - https://rnacentral.org/rna/URS000230DC70/4896
[SPNCRNA.1669](https://www.pombase.org/gene/SPNCRNA.1669) - https://rnacentral.org/rna/URS000019CED9/4896
[SPNCRNA.2479](https://www.pombase.org/gene/SPNCRNA.2479) - https://rnacentral.org/rna/URS000230D749/4896
[SPNCRNA.2656](https://www.pombase.org/gene/SPNCRNA.2656) - https://rnacentral.org/rna/URS000230D399/4896
[SPNCRNA.2777](https://www.pombase.org/gene/SPNCRNA.2777) - https://rnacentral.org/rna/URS000230DE13/4896
[SPNCRNA.2990](https://www.pombase.org/gene/SPNCRNA.2990) - https://rnacentral.org/rna/URS000230E2E9/4896
[SPNCRNA.3131](https://www.pombase.org/gene/SPNCRNA.3131) - https://rnacentral.org/rna/URS000230DDBA/4896
[SPNCRNA.4841](https://www.pombase.org/gene/SPNCRNA.4841) - https://rnacentral.org/rna/URS000230D36A/4896

And one that RNAcentral lists as 5S ribosomal RNA:
[SPNCRNA.4731](https://www.pombase.org/gene/SPNCRNA.4731)  - https://rnacentral.org/rna/URS000230E3F3/4896

**Comment by ValWood** [comment]
For all these the annotated feature always seems to be on the opposite strand, and I'm sure that's correct so maybe this is some sort of bug in R2DT

1. Check strand of annotated feature is correct.
2. Check cooridinates match and it isn't a divergent copy

That should be enough to see if its an annotation error or a bug

**Comment by ValWood** [comment]
no huge hurry, but when you want a change

**Comment by PCarme** [comment]
I had a look at these ncRNAs. All of them have a tRNA annotated on the opposite strand in PomBase, exactly at the position where RNA Central detects it (based on the Rfam matching at the bottom of the pages). Some of them even have 2 tRNAs on the opposite strand, and both are indicated in RNA Central. 
It might be a bug since the RNA Central pages give the coordinates of the tRNA structure in the opposite direction compared to the ncRNA, it might predict the structures in the wrong direction. Alternatively, it may predict the structures in both directions, but none of these ncRNA match any Rfam. 

Regarding the coordinates, all of these ncRNAs have matching coordinates in PomBase and RNA Central, but they are all indicated on the reverse strand in RNA Central, while SPNCRNA.2529, SPNCRNA.2656, SPNCRNA.2777 and SPNCRNA.2990 are located on the forward strand in PomBase.

**Comment by ValWood** [comment]
OK @PCarme  thanks for checking this.

reported https://github.com/r2dt-bio/R2DT/issues/149

**Comment by ValWood** [comment]
Thanks R2DT have fixed this for the next release. They are fast!

cc @kimrutherford
