### ISSUE TITLE
update non-sporulation viability (deletion project)

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#448]
From Antonia
move to inviable cell population? You don't know if it is sporulation, germination or vegetative growth that is blocked. 

(I think there is a paper from henry Levin which uses a different method, and distinguishes between these)

Original comment by: ValWood

**Comment by ValWood** [comment]
from

https://github.com/pombase/curation/issues/988

Val
kap109 has
viable spore population (I don't know what this means, although I appear to have requested the the term
I also has inviable vegetative cell population for the same phenotype.
I guess it just means that the cells germinate, and then die? but isn't this an odd term?

Antonia
We wanted to be able to distinguish populations of spores that cannot germinate, from population of spores that can germinate but not go on and form colonies.
This is because of the cases where genes are annotated to "inviable vegetative cell population" but actually it is because the spores were inviable, the vegetative cells are fine.
Conversely, for kap109 you can see that the spores are completely fine, the problem is in the vegetative phase.


Val
I mean not all spores germinate. Some are inviable.
"viable spore population" as a population phenotype looks incompatible with a cellular phenotye of "inviable spore"
That's why I asked what it meant...

Val
OK got it (I think).
we need to add this for those where this for eg:

inviable after spore germination with normal, unseptated germ tube morphology
and all the others which are inviable after spore germination...

and everything viable?
etc

Val
I can see we would want to capture "inviable spore population" for those which can't sporulate , but how useful is the term "viable spore population" (its very annotation incomplete based on current knowledge).

**Comment by ValWood** [comment]
I'll take this one, I need to figure out what to do....
