### ISSUE TITLE
Waiting for updates at SGD

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#569]
when annotated in SGD there is a new cell paper that  might be informative for heh2

Original comment by: ValWood

**Comment by ValWood** [comment]
also a MF for Coq6
is Responsible for the C4-Deamination Reaction in Coenzyme Q Biosynthesis in Saccharomyces cerevisiae. PMID: 2626078

**Comment by Antonialock** [comment]
still not updated

**Comment by ValWood** [comment]
ok I asked them

**Comment by ValWood** [comment]
still not updated

**Comment by ValWood** [comment]
not updated

**Comment by ValWood** [comment]
http://www.pombase.org/spombe/result/SPAC3H1.05#ortholog

when sgd curate
Ast T, Michaelis S, Schuldiner M. Related Articles
The Protease Ste24 Clears Clogged Translocons.
Cell. 2016 Jan 14;164(1-2):103-114.
PMID: 26771486

transferred from 
https://github.com/pombase/curation/issues/786

**Comment by ValWood** [comment]
some ISO updates aro8,aro9, hfd1

Coenzyme Q (Q) is a redox lipid that is central for the energetic metabolism of eukaryotes. The biosynthesis of Q from the aromatic precursor 4-hydroxybenzoic acid (4-HB) is understood fairly well. However, biosynthetic details of how 4-HB is produced from tyrosine remain elusive. Here, we provide key insights into this long-standing biosynthetic problem by uncovering molecular details of the first and last reactions of the pathway in the yeast Saccharomyces cerevisiae, namely the deamination of tyrosine to 4-hydroxyphenylpyruvate by Aro8 and Aro9, and the oxidation of 4-hydroxybenzaldehyde to 4-HB by Hfd1. Inactivation of the HFD1 gene in yeast resulted in Q deficiency, which was rescued by the human enzyme ALDH3A1. This suggests that a similar pathway operates in animals, including humans, and led us to propose that patients with genetically unassigned Q deficiency should be screened for mutations in aldehyde dehydrogenase genes, especially ALDH3A1.

PMID: 27693056

**Comment by ValWood** [comment]
eiF4G
Abstract
The eukaryotic translation initiation factor, eIF4G plays a key functional role in the initiation of cap-dependent translation by acting as an adapter to nucleate the assembly of eIF4F complex. Together with poly(A) binding protein and eIF3, eIF4F subsequently triggers the recruitment of 43S ribosomal pre-initiation complex to the messenger RNA template. Since eukaryotes primarily regulate translation at the level of initiation, eIF4G is implicated in the control of eukaryotic gene expression. Remarkably, emerging evidence in Saccharomyces cerevisiae indicates that eIF4G also plays a key role in nuclear mRNA biogenesis and surveillance - a finding that is in agreement with its nuclear distribution. Here, we focus on the functional involvement of eIF4G in the nucleus in modulating pre-mRNA splicing, mRNA surveillance, and possibly in much-debated nuclear translation. Notably, the nature of the biochemical role of this protein in the major events of cellular mRNA metabolism emphasizes that this crucial protein factor may serve as a general integrator of mRNA functional states by acting as an adapter molecule.

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/27294321?dopt=Abstract
for pho2

**Comment by ValWood** [comment]
PMID:22562153 opy1

**Comment by ValWood** [comment]
Sitron CS, Park JH, Brandman O. 	  Related Articles
Asc1, Hel2, and Slh1 couple translation arrest to nascent chain degradation.
RNA. 2017 Feb 21;. [Epub ahead of print]
PMID: 28223409

**Comment by ValWood** [comment]
https://www.pombase.org/gene/SPAPB1A10.16

**Comment by ValWood** [comment]
"DNA scrunching"
There is a 2006 Science paper about this activity, but no term in GO?

Nucleic Acids Res. 2020 Jan 25. pii: gkaa040. doi: 10.1093/nar/gkaa040. [Epub ahead of print]
The C-terminal tail of the yeast mitochondrial transcription factor Mtf1 coordinates template strand alignment, DNA scrunching and timely transition into elongation.
Basu U1,2, Lee SW3, Deshpande A1, Shen J1,2, Sohn BK3, Cho H3, Kim H3,4, Patel SS1.
Author information

**Comment by ValWood** [comment]
| Schmidt CC, Vasic V, Stein A. | Related Articles
-- | -- | --
  | Doa10 is a membrane protein retrotranslocase in ER-associated protein degradation.
  | Elife. 2020 Jun 26;9.
  | PMID: 32588820

**Comment by ValWood** [comment]
coq6
SGD never responded
can use human Q9Y2Z9
4-hydroxy-3-all-trans-hexaprenylbenzoate + 2 H+ + O2 + 2 reduced [2Fe-2S]-[ferredoxin] = 3,4-dihydroxy-5-all-trans-hexaprenylbenzoate + H2O + 2 oxidized [2Fe-2S]-[ferredoxin]

**Comment by ValWood** [comment]
- [ ] coq6can use human Q9Y2Z9
4-hydroxy-3-all-trans-hexaprenylbenzoate + 2 H+ + O2 + 2 reduced [2Fe-2S]-[ferredoxin] = 3,4-dihydroxy-5-all-trans-hexaprenylbenzoate + H2O + 2 oxidized [2Fe-2S]-[ferredoxin]

- [ ]    Doa10 ISS-> GO:0030970
   PMID: 32588820

- [ ] ste24 - > GO:0031204 posttranslational protein targeting to membrane, translocation
PMID: 26771486

**Comment by ValWood** [comment]
yay,yay
