### ISSUE TITLE
filtered by GOA 

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#591]
This is the list of things filtered by GOA (After I filtered the RNA annotations)

There are quite a lot. Some are probably valid ( if the SGD ID is not recognized for example, and we should have an internal check for that). Others I'm not so sure about  like, I thought it was valid to use a GO:ID for a "guilt by association" IPI annotation ......

Anyway we need to fix some and query some if we are to get GOA to represent all of our data.

Original comment by: ValWood

**Comment by mah11** [comment]
note: retrieve attachment from SF ticket
http://sourceforge.net/p/pombase/curation-tasks/607/

**Comment by mah11** [comment]
I had another look at these, and I think it would make sense to revisit when we have an updated report from GOA (or Jenkins, if these checks get incorporated soon).

- I fixed some things back when this ticket was opened (on SF), and a few more just now.

- The updates to the UniProt ID mapping should make some of the errors go away.

- We're waiting to hear if they've corrected whatever was generating false positives for a lot of coincident_with(SO:nnn) extensions (our helpdesk ticket https://rt.sanger.ac.uk/Ticket/Display.html?id=465712 ; GOJIRA ticket 819).

When we do get a fresh report, actual errors will stand out better and I/we can fix them then. We can also ask around GO:
- whether GO CC is allowed in 'with' for IPI
- whether CBS:TMHMM is allowed in 'with' for ISS (and if not, what, if anything, to use instead)
- whether their set of allowed ID prefixes for ISS and its subtypes is complete (there are errors for some MOD IDs that look OK)

**Comment by ValWood** [comment]
I'm trying to get the updated file.
We should  keep a list of the errors and
i) incorporate them into our checks
ii) As GO to include then in the jenkins checks/ or upload checks

**Comment by mah11** [comment]
GOA should send reports to the contact emails in the gene_association.*.conf files (i.e. the helpdesk, for us) whenever they're generated.

I think GO's plan is to add the GOA checks to Jenkins, although I'm sure it won't hurt to prod them again. If they do so in a timely fashion (ha ha) it won't be critical for us to deploy them anywhere else, because we can (and I do) run the Jenkins checks via owltools.

**Comment by ValWood** [comment]
See later e-mail ;)

**Comment by mah11** [comment]
Thanks. Frankly, I don't think GOA should expect us (or anyone else) to act on anything they don't send through proper channels, i.e. to the listed contact email. If it's not ready for that, it's not ready to be taken seriously.

**Comment by ValWood** [comment]
They didn't. I asked for the file because I know they drop pombe annotations from GOA, and many seem to be for reasons we can easily fix.....missing with fields etc. It's got to be good to fix these ?

**Comment by mah11** [comment]
Well, I would also say they shouldn't actually use any filtering on the data they present to the public until and unless the checking system is good and ready to also be used to provide feedback to submitters via established channels.

**Comment by mah11** [comment]
GO has moved their side of this to https://github.com/geneontology/go-site/issues/123

**Comment by mah11** [comment]
I've been through the GOA check report from 2016-03-16 and fixed stuff. I'm going to close this, because most of the comments are out of date, and we can open new tickets if anything comes up in subsequent reports.

Some points:

Almost 90% of the flagged annotations are for ncRNAs, so there's no UniProtKB ID. I presume there's nothing to do about those but wait for the checks to take RNACentral IDs into account.

There are a handful of protein-coding genes, and a pseudogene and a transposon, that also don't have matching UniProt accessions. I'll assume those will be handled, or not, in their own right and not make a separate fuss over the GO annotation checks.

Another 40 use not_* extension relations, so they're waiting for GO to figure out what to do about negation and extensions. I've opened #877 for them.

There are a few where I can't see why they failed the checks, so I'll ask at some point (though I may wait and see if the same things crop up in the next report). Some probably fall under the https://github.com/geneontology/go-site/issues/123 umbrella.

files in Dropbox/pombase/ontologies/GO/GO_annotation_misc/syntax_checks/
