### ISSUE TITLE
are these extensions correct?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#659]
These look a bit odd
nuclear chromatin coincident with PomBase gene?
Should these be something else?

GO:0000790	coincident_with(PomBase:SPAC2E12.02),exists_during(GO:0034605)
GO:0000790	coincident_with(PomBase:SPAC664.11),exists_during(GO:0034605)
GO:0000790	coincident_with(PomBase:SPBC32H8.12c)
GO:0000790	coincident_with(PomBase:SPBP35G2.16c),exists_during(GO:0034605)
GO:0000790	coincident_with(PomBase:SPCC622.08c)
GO:0000790	coincident_with(PomBase:SPCC622.09)

From the PomBase docs:
http://curation.pombase.org/pombase-trac/wiki/ListOfRelationsForGO

coincident_with	use for localization to chromatin at a specific sequence or type of sequence region (SO ID); particularly useful for annotating ChIP results	orc1 GO:0000790 coincident_with (SO:0000296) = localizes to 'nuclear chromatin' at 'origin_of_replication'

**Comment by mah11** [comment]
These are correct; update the documentation.

Note that even the GO relations file has the range incomplete, although its text comment acknowledges that it can be used for genes.

**Comment by ValWood** [comment]
What does it mean? It sounds like protein colocalization? Do we use it like that?

**Comment by mah11** [comment]
"Coincindent_with" is what GO finally came up with after months of prodding by me and Karen C for a relation to use with annotations to CC chromatin, which we needed because of the GO decision that ChIP data shouldn't be used to support MF chromatin binding annotations.

So it's CC coincindent_with SO sequence feature or MOD gene, and the CC is pretty much always one of the chromatin terms. The extensions is which bit of chromatin (i.e. at which gene(s) or sequence feature(s)) a gene product is found at by ChIP.

(most of the above copied & pasted from email)

**Comment by ValWood** [comment]
fixed
