### ISSUE TITLE
check and standardize "disruption" allele descriptions

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#664]
follow on from 
https://github.com/pombase/canto/issues/944
> For the others, I think we should check and standardise

for example:
spo15::ura4+,SPAC1F3.06c,spo15,spo15::ura4+disruption,f51c10788015bf25
has the allele name repeated in the 'description' field

and we could probably have some recommended shorthand syntax for others:
ctf18::ura4+,SPBC902.02c,ctf18,disruption; ura4+ inserted after nucleotide position 1603 of coding region,a5072a23ae384ac4

as they look a bit unwieldy:
http://www.pombase.org/spombe/result/SPBC902.02c#fission_yeast_phenotype-cell_phenotype

perhaps?
like ctf18:ura4+(nt1603)

Once we are happy that all are correctly described in this file
https://www.dropbox.com/s/yqdk8z6syot7iiq/other_alleles.csv?dl=0

Kim can migrate them to description type 'disruption'

**Comment by mah11** [comment]
From the related Canto ticket (https://github.com/pombase/canto/issues/681):

-----
Val: 
I think the description can be optional but we should have some text to appear under the allele description box suggesting a recommended format e.g.

cdc2+::marker, cdc2+::marker(nt343)

-----

Midori:
The disrupted gene should NOT have the "+" because it is not wild type if it is disrupted.

Use cdc2::ura4+ or cdc2::ura4+(nt343) or cdc2::ura4+(nt123-1234)

**Comment by mah11** [comment]
closing because disruptions flagged and fixed in #701
