### ISSUE TITLE
curate Yoshida localization paper fully

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#754]
crm targets etc.
Needs to be done in spreadsheet, but some of the data isn't in the Supp tables.
Mailed Yoshida.

Also see helpdesk ticket
https://rt.sanger.ac.uk/SelfService/Display.html?id=499829

@JackyVH (to follow)

**Comment by mah11** [comment]
PMID?

**Comment by ValWood** [comment]
Sorry, massive assumption

ORFeome cloning and global analysis of protein localization in the fission yeast Schizosaccharomyces pombe.
PMID: 16823372

**Comment by mah11** [comment]
OK, so that's mostly covered by the GO_ORFeome_localization files, and we just need the list of genes/proteins affected by Crm1 inactivation?

Hmm. GO is deprecating dependent_on, so the best thing will probably be to use phenotype annotations, which we can do if we stretch the meaning of "knockdown" to cover the leptomycin B effect.

**Comment by ValWood** [comment]
If these are considered to be crm targets (i.e. if lepB selectively inhibits crm1?), it could be
GO:0006611 - protein export from nucleus has_input target_gene?
or even nuclear export signal receptor activity?
with IMP

Anyways the data isn't in the supp. tables as far as I can see....so waiting to see if it can be supplied...

**Comment by mah11** [comment]
This paper only shows that some proteins end up in different locations with leptomycin than without. I don't think I would normally interpret that as this paper showing what Crm1 does. Everything else cites other papers for the role of Crm1 (including that leptomycin B specifically inhibits Crm1).

**Comment by mah11** [comment]
and yeah, all moot unless you get the gene list ...

**Comment by ValWood** [comment]
I have the list from Minoru. I see what you mean for the phenotype, there is no mutant. durr.
I think  knockdown might be misleading though...

Options for phenotypes
i) wt crm1 knockdown
ii) wt crm1 "inactivation by drug" or something else (new option for inactivation)

Or GO terms
if LepB really is specific for the inactivation of crm1 (this is well known, but I guess we could not rule out any 'off target effect'), this could be considered an assay for  crm1 cargo and could we annotate the gene products which are no longer exported as has_substrate ? We could use EXP instead of IDA as the evidence is probably now what most people would considera direct assay....

I don't think anyone would argue that this experiment did not identify the cargoes of crm1. I think the benefits of adding term likely overrule the  slight chance that there are a couple of spurious cargo in here. This is *really* useful data for cell cycle researchers because of the effect of nucleocytoplasmic transport on  various cell cycle checkpoints and transitions.

**Comment by ValWood** [comment]
[LMB285.xlsx](https://github.com/pombase/curation/files/37714/LMB285.xlsx)

**Comment by mah11** [comment]
I'm not super-comfortable with GO, but it is true that phenotype annotations are also a poor fit since we haven't used phenotype for any other cases of inactivating an already-expressed wild-type gene product.

It certainly isn't IDA, since they haven't shown Crm1 physically interacting with any of the mislocalized proteins. I wish GO allowed a way to use IC here, since we're inferring that the mislocalized proteins are Crm1 cargo from a combination of the localization data in this paper and a lot of stuff we know from other papers about (a) Crm1 itself and (b) the effect of leptomycin B.

I think what I'm dissatisfied with is attributing the conclusion that "Crm1 moves these proteins" solely to this paper ... but I suppose that's a limitation on GO annotation generally. If GO were responsive I'd ask them to broaden the use cases, and allowable 'with' entries, for IC.

In this reality, to me it's a toss-up between abusing "wt knockdown" (on the grounds that there's less functional Crm1) or using GO BP annotations with EXP. I'm not going to lose sleep over which one we do.

**Comment by ValWood** [comment]
Helena:
Thank you so much for getting hold of this and looking into this for us. In terms of categorising these would 'localisation sensitive to LMB treatment' work? I agree you have to be a bit careful labelling them as Crm1 cargoes in case of other effects of LMB treatment. I will ask around the lab and see what others think though too (I don't think Jacky is in today but I'll speak to her on Monday).

**Comment by ValWood** [comment]
IIRC  *I think* these are expressed form nmt promoter in WT background. This would solve the problem

could be
allele:gene x overexpression 
term: protein mislocalized term  
condition: LMB?
?

**Comment by Antonialock** [comment]
I don't like it...I think it is misleading (especially in the summary view). it's not really a phenotype of the overexpressed allele.

**Comment by Antonialock** [comment]
If you really really think it is important to capture this then I agree with midori:
In this reality, to me it's a toss-up between abusing "wt knockdown" (on the grounds that there's less functional Crm1) or using GO BP annotations with EXP. I'm not going to lose sleep over which one we do.

**Comment by ValWood** [comment]
Why?
its a phenotype of the over expressed allele when it's LMB treated? (the mislocalized GPs would be extensions). I don't know what the exact term would be  
abolished localization of protein to cytoplasm? (if its nuclear retention)

**Comment by ValWood** [comment]
yeah ignore me. It doesn't work at al....
