### ISSUE TITLE
a question about Canto display text

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#766]
Not sure about this....
I'm not sure if these relations are totally correct
GO:0006468      is_a    has_input       ProteinID phosphorylates  0,1     user
GO:0006473      is_a    has_input       ProteinID acetylates      0,1     user
GO:0006486      is_a    has_input       ProteinID glycosylates    0,1     user 

This is OK, but if the relation really were "phosphorylates' the extension should be on the MF term. We would only se this is if  was "involved in phosphorylation"   but we didn't know if it was the substrate....

I guess it doesn't really matter, as when we check we can always transfer any appropriate to the MF term for the time being.... 
I just wondered what you thought.......

**Comment by mah11** [comment]
I think it's probably not a big deal, because the goal here is to get users to tell us which protein is getting modified, rather than to use the most precisely, pedantically correct text imaginable. The existing text serves the purpose well enough.

That said, the only argument against changing to "phosphorylation of", "acetylation of", etc. would be if you don't want to spend the few minutes editing the config file.

**Comment by ValWood** [comment]
OK I changed.
