### ISSUE TITLE
should we do these as conditions?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#777]
![conditions](https://cloud.githubusercontent.com/assets/7359272/11587361/b5668c1a-9a70-11e5-9295-2de641759bbf.jpg)

**Comment by ValWood** [comment]
i.e, i can't remember why we don't

**Comment by Antonialock** [comment]
I'm so unsure what to do about these. I don't really like doing them as conditions or child terms because if you query for all genes annotated to "elongated vegetative cell" then you might not want the ones that are stress-dependent? There's also the extra fypo crating-terms workload to consider...

I normally just stick them in the "sensitive to X" bin (usually they will have a growth defect) but that also feels a bit unsatisfactory. Especially in cases like the one you had a few weeks ago where the PM potential changed during X. 

What do you think is best in terms of querying annotations, annotation specificity and time spent making fypo terms?

**Comment by mah11** [comment]
The relevant wiki page suggests that we haven't specifically discussed these terms, although it does seem that we've mostly opted to use conditions for chemicals. I don't really have a strong preference, as long as we're consistent.

http://curation.pombase.org/pombase-trac/wiki/PrePostComposePhenotype

p.s. It's a lot more useful to put term names in tickets as text, because then they can be read in any mail client, and copied/pasted.

**Comment by ValWood** [comment]
numbers 
...hydrogen peroxide (1) spc1
...non ionic osmotic stress (1) spc1
...osmotic stress (1) sum1 (O-EX?)
...response to caffeine (4) int6, mkh1, pek1,pmk1
...ionizing radiation (1) crb2

**Comment by ValWood** [comment]
out of 820  7 genes

**Comment by ValWood** [comment]
decision:
https://github.com/pombase/fypo/issues/2970
