### ISSUE TITLE
expression  choices sub optimal

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#846]
Quite often I see this scenario

lated when an asynchronous culture of temperature- sensitive cdc2-L7 cells producing low levels of T167 E from a multi-copy plasmid was shifted to 36° C (Gould et al. 1991).

 For these do you use  overexpression, or not specified.

Then, what do you do if they use  a plasmid for low expression and then another promoter for high expression with different phenotypes for the same allele?

**Comment by mah11** [comment]
I've shoved most of the plasmid expression I've seen into "not specified" because they seldom show a comparison with truly endogenous ... but it is suboptimal. 

I thought we talked a bit about adding a "plasmid expression" option that wouldn't explicity say up or down, but would give a bit more info than not specified at all, but obviously we never got round to implementing it.

**Comment by ValWood** [comment]
covered?
