### ISSUE TITLE
abolished mitotic sister chromatid separation vs abnormal cell cycle arrest in mitotic metaphase

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#847]
abnormal cell cycle arrest in mitotic metaphase
has
abolished mitotic sister chromatid separation
as a "suggestion".

If we have any terms as suggestions, it should mean that the annotation is transitive so if you choose the more specific term, you are automatically annotating to the parent.

In this case it isn't 

![transitivity](https://cloud.githubusercontent.com/assets/7359272/13604571/509918c8-e53b-11e5-8823-7c5e8259d571.jpg)

I'm not sure what the problem is or the solution.

**Comment by ValWood** [comment]
These 2 terms are a bit chicken and egg. If mitotic sister chromatid separation is abolished, you are arrested in metaphase.
if you are arrested in metaphase, sister chromatids haven't separated.

Actually did we discuss this yesterday?

**Comment by mah11** [comment]
Maybe has_part is a better link type after all - if you're arrested in metaphase, you don't get sister chromatid separation, and you've got chromosomes aligned in the middle of the spindle.

As for the search, it might be worth checking again after the update, because it's probably using FYPO from before the changes I did yesterday, when the connection between FYPO:0000620 and FYPO:0001946 wasn't direct. After that, it should work as you expect (per Jira tickets PB-1962 and PB-2027).

**Comment by ValWood** [comment]
OK assign to me to check when you are done. I couldn't remember where we were up to.

**Comment by mah11** [comment]
The FYPO stuff got done yesterday. I'm just not sure Mark updates the ontologies for the searches between releases. If he doesn't, the changes won't be there yet.

**Comment by ValWood** [comment]
I think he uses the same ontologies that Kim uses for the release. if so I'll bump to my next release check. no hurry.

**Comment by ValWood** [comment]
That worked!
