### ISSUE TITLE
check meiotic  nuclear division or meiotic cell cycle

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#907]

**Comment by ValWood** [comment]
SPBC32H8.11.1		GO:0045836	positive regulation of meiotic nuclear division	915dd27f11d0b65d	PomBase
SPAC24H6.05.1		GO:0045836	positive regulation of meiotic nuclear division	915dd27f11d0b65d	PomBase

**Comment by Antonialock** [comment]
Did you look at the abstract for this paper? I don't know if I should make process annnotations from it, but if I do then meiotic nuclear division seems ok (or meiosis I?)

In meiosis, the fission yeast nucleus displays an elongated morphology, moving back and forth
within the cell; these nuclear movements continue for approximately 2 h before meiotic
nuclear divisions. Meiotic DNA replication occurs in an early phase of the nuclear movements
and is followed by meiotic prophase. Here we report that in mutants deficient in meiotic
DNA replication, the duration of nuclear movements is strikingly prolonged to four to 5 h.
We found that this prolongation was caused by the Cds1-dependent replication checkpoint,
which represses expression of the
mei4
+
gene encoding a meiosis-specific transcription factor.
In the absence of Mei4, nuclear movements persisted for more than 8 h. In contrast, overpro-
duction of Mei4 accelerated termination of nuclear movements to approximately 30 min.
These results show that Mei4 is involved in the termination of nuclear movements and that
Mei4-mediated regulatory pathways link a DNA replication checkpoint to the termination of
nuclear movements.

**Comment by ValWood** [comment]
From this abstract, because it talks about nuclear movement and DNA replication, I would say its upstream of  meiotic nuclear division?
I would go up to "meiotic cell cycle"

**Comment by mah11** [comment]
oh that's annoying - from other papers we've got the idea that the nuclear movement happens entirely during prophase I, not before. argh.

**Comment by ValWood** [comment]
Oh that might be correct that it is during prophase 1...... I still think its incorrect to say that these TFs are directly regulating  meiotic nuclear division. They are  required for the transcription of many genes required for the meiotic cell cycle,  and it won't occur if the gene products are not present, but are they directly regulating meiotic division????

**Comment by ValWood** [comment]
duplicate of https://github.com/pombase/curation/issues/1085
