### ISSUE TITLE
extension problem cdc2 GO:0004674 PMID:16950131

### ISSUE THREAD

**Issue by mah11** [pombase/curation#923]
The Canto log has this:

warning in 3472d1b25692f40c: directly_inhibits() not allowed for molecular_function

directly_inhibits not only isn't configured for Chado to allow it for MF, it's not an available extension relation at all. 

I added this in TG in case it helps - part_of(GO:1905183),happens_during(GO:0001100) would get fairly close, but I'll leave it for you to decide what to put. (We need LEGO to fully capture "phosphorylates Clp1 to inhibit its protein S/T phosphatase activity and thereby contribute to negative regulation of exit from mitosis".)

**Comment by Antonialock** [comment]
hmm, I'd swear I never used "directly inhibits" :-)

so is GO:1905183
"negative regulation of protein serine/threonine phosphatase activity"?

**Comment by mah11** [comment]
doh, yes, I meant to copy the term name here ... I even remember hitting 'copy' but obviously I forgot 'paste'

Anyway, I assigned the ticket to you because the session generally is yours - but it has the message "changed extension to: has_substrate PomBase:clp1 , directly_inhibits GO:0004865 , part_of GO:0001100". Could that be Val? (wasn't me)

**Comment by Antonialock** [comment]
Cool cheers! 
It is now: 
has_substrate PomBase:clp1 
part_of GO:1905183 
happens_during GO:0001100

**Comment by ValWood** [comment]
Leave this one with me. I'm trying to establish with go what relationship to use when 
we want to capture on  for example a protein kinase activity is inhibiting or activating (so that we don't have concurrent annotation fro the same experiment to  phosphatase inhibitor, and the like.  

I talked about it with  them already but  I forgot what the outcome was. I know  it can't be "directly inhibits"
because you inhibit an activity not a gene product?

**Comment by ValWood** [comment]
> so is GO:1905183
"negative regulation of protein serine/threonine phosphatase activity"?

I want to avoid this....if possible, we want to represent onMF not as BP, its direct so this has a broader meaning

**Comment by ValWood** [comment]
transferred to my ongoing cdc2 QC ticket
https://github.com/pombase/curation/issues/963
