### ISSUE TITLE
rqh1 term diff?

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#947]
I was looking at rqh1 for the paper I am curating where it is functionally linked to cut8  (out of my comfort zone)

I spotted
GO:1903221	regulation of mitotic recombination involved in replication fork processing	IMP		Iraqui I et al. (2012)	

but other genes have
GO:1990426	homologous recombination-dependent replication fork processing

maybe  GO:1990426 is a better term to use?

Is there a difference between
recombination-dependent replication fork processing
and
recombination involved in replication fork processing

**Comment by ValWood** [comment]
maybe noeither of these terms are quite right.
Isn't it more like

resolution of (mitotic) recombination intermediates involved in replication fork processing?
(maybe not all the papers show this, but it seems that maybe a term like this would be the most specific and pinpoint the role in fork processing?)

**Comment by ValWood** [comment]
Also,
I notice that rqh1 is ISS'd to DNA unwinding during replication (one of my old ones I think).
Do you think that is correct? I'm not even sure this is a replication helicase in cerevisiae?
Val

**Comment by mah11** [comment]
The GO:1903221 and GO:1990426 annotations come from papers Sarah Lambert curated (coincidentally, the same papers that came up wrt your question about DNA replication annotations a week or two ago); as I mentioned, I did the session approvals but had to trust that Sarah picked sensible GO BP terms because I don't know this area particularly well. It looks like I added terms in TG based on her comments. The two terms used for rqh1 come from different papers, with different evidence, so that may well account for why different terms are used (I can reread the papers to confirm if it's important).

PMID:23093942 (40fd88a127db667a)
PMID:25313826 (e8a53aa5aa4d49f7)

I haven't really done much annotation for rqh1 myself (mostly phenotypes as they've come up in papers on tangentially related topics). I do not know the precise role of rqh1 in fork processing, so I don't know whether "resolution of (mitotic) recombination intermediates involved in replication fork processing" is applicable. How high a priority is it to investigate further?

As for the existing terms, it looks like GO:1903221 should be part_of GO:1903211 and the names might as well match. I'll open a GO ticket for that.

re ISO: The unwinding annotation could probably be moved up to 'DNA duplex unwinding' GO:0032508 for both the S. cerevisiae SGS1 IDA and the inferred pombe annotation -- SGD's annotation dates back to 2002, when GO:0006268 was named 'DNA unwinding'. The cited paper unequivocally supports annotation to unwinding but doesn't address whether the context is replication, repair or something else.

**Comment by ValWood** [comment]
OK  could you  open the GO ticket you suggested, and unassign yourself.

I'll  ask SGD to check the annotation (and most likely remove the ISS).

Then we can leave this one open for a while and whoever fully curates rqh1 fully can double check and close eventually (We can add a low priority label)

**Comment by mah11** [comment]
https://github.com/geneontology/go-ontology/issues/12481

**Comment by ValWood** [comment]
I reported to SGD and I'll remove the ISS because we already have experimental to 
"DNA unwinding"

I think this can close, because your GO suggestions will  fix  my other concern.
