### ISSUE TITLE
assayed using (FYPO:0003577)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#968]
abolished plasma membrane to vacuole transport after nitrogen starvation

cant use assayed using with this term.

not sure how far up graph this needs to go.

**Comment by ValWood** [comment]
Also, I want to use assayed_using with
decreased microtubule-based movement

(that sounds wrong doesn't it?, I think I needed microtubule-based transport...hang on....)

**Comment by mah11** [comment]
I'd like to handle this as proposed in the linked FYPO ticket, i.e.


    add narrow synonym 'abolished plasma membrane to vacuole protein transport after nitrogen starvation';
    add comment to explain that proteins or other stuff can be transported, and that if transport of a protein was assayed, put it in an extension;
    add to the extension config to allow (but not require) a gene ID to represent an assayed protein.

**Comment by ValWood** [comment]
Oh I get it, this can have the XP? then we can add others as required?

**Comment by mah11** [comment]
No, the term in the original summary (FYPO:0003577) doesn't have an xp, because it doesn't refer to a single GO term anyway (there isn't a 'plasma membrane to vacuole transport' term; it's probably equivalent to GO:0048227 'plasma membrane to endosome transport' followed by GO:0045324 'late endosome to vacuole transport').

**Comment by mah11** [comment]
all adjustments made

FYPO changes in
edit file: 87bbd5a48383ecf64dfdfde1fc48c7f8b8c05389
release: a1a90675d29890871922540ab49849611cfd8bc0
