### ISSUE TITLE
reference corrections from GOA syntax checks

### ISSUE THREAD

**Issue by mah11** [pombase/curation#981]
noting here for posterity

The July 2016 syntax checks from GOA flagged loads of annotations as citing a "Reference not appropriate for evidence code". Some look spurious (GO_REF:0000024 really sounds like it's exactly the thing for ISO), but others did need fixing.

- I realized that ISS or ISM annotations that have an InterPro or Pfam ID in 'with' should use GO_REF:0000050 (Manual transfer of GO annotation data to genes by curator judgment of sequence model), not GO_REF:0000024. Corrected in contig files.

- I've also made the executive decision that any NAS annotations can use our GO_REF:0000051 (keywords) instead of GO_REF:0000001 (unpublished). It's not actively misleading, and we have a decent chance of replacing all NASs in this lifetime, so it should be close enough.

- IC annotations with GO_REF:0000001 are now being flagged, but will have to be upgraded individually (see #449). This is on my Friday-afternoon back burner anyway, so I'll plug away at it a little at a time, perhaps with slightly less-low priority now that something's noticing.

Tickets opened
- for ISM/ref 24: https://github.com/geneontology/go-annotation/issues/1417
- for IC/ref 24 or 50: https://github.com/geneontology/go-annotation/issues/1418

**Comment by ValWood** [comment]
Re:
I've also made the executive decision that any NAS annotations can use our GO_REF:0000051 (keywords) instead of GO_REF:0000001 (unpublished). It's not actively misleading, and we have a decent chance of replacing all NASs in this lifetime, so it should be close enough.

Also, the ones in the flat file (which is probably most of those retained after filtering)  *were* originally created from a keyword mapping  from the product descriptions that I made in the early days.....if that makes you feel better....
